#!/usr/bin/env python3
"""
Import comprehensive world university rankings from 5 major ranking systems:
- QS World University Rankings 2026
- US News Best Global Universities 2026
- Times Higher Education (THE) World University Rankings 2026
- ARWU (Shanghai Ranking) 2025
- CWUR World University Rankings 2025

Each university's ranking data is unique (no duplicates in any list).
Uses fuzzy name matching to update the database.
"""

import sqlite3
import re
import os
import sys
from difflib import SequenceMatcher

DB_PATH = '/Users/wangfeng/.openclaw/workspace/school-badge-website/database.db'

# ─────────────────────────────────────────────────────────────────────────────
# QS World University Rankings 2026 — Top 200 (no duplicates)
# Format: (rank, name_en, name_cn, country)
# ─────────────────────────────────────────────────────────────────────────────
QS_2026 = [
    (1, "Massachusetts Institute of Technology", "麻省理工学院", "United States"),
    (2, "Imperial College London", "伦敦帝国学院", "United Kingdom"),
    (3, "University of Oxford", "牛津大学", "United Kingdom"),
    (4, "Harvard University", "哈佛大学", "United States"),
    (5, "University of Cambridge", "剑桥大学", "United Kingdom"),
    (6, "Stanford University", "斯坦福大学", "United States"),
    (7, "ETH Zurich", "苏黎世联邦理工学院", "Switzerland"),
    (8, "National University of Singapore", "新加坡国立大学", "Singapore"),
    (9, "University of Pennsylvania", "宾夕法尼亚大学", "United States"),
    (10, "Tsinghua University", "清华大学", "China"),
    (11, "Peking University", "北京大学", "China"),
    (12, "University of California, Berkeley", "加州大学伯克利分校", "United States"),
    (13, "Columbia University", "哥伦比亚大学", "United States"),
    (14, "University of Toronto", "多伦多大学", "Canada"),
    (15, "Johns Hopkins University", "约翰斯·霍普金斯大学", "United States"),
    (16, "University of Chicago", "芝加哥大学", "United States"),
    (17, "Cornell University", "康奈尔大学", "United States"),
    (18, "Yale University", "耶鲁大学", "United States"),
    (19, "Nanyang Technological University", "南洋理工大学", "Singapore"),
    (20, "University of Michigan-Ann Arbor", "密歇根大学安娜堡分校", "United States"),
    (21, "Princeton University", "普林斯顿大学", "United States"),
    (22, "Duke University", "杜克大学", "United States"),
    (23, "Northwestern University", "西北大学", "United States"),
    (24, "University of Edinburgh", "爱丁堡大学", "United Kingdom"),
    (25, "University of California, Los Angeles", "加州大学洛杉矶分校", "United States"),
    (26, "King's College London", "伦敦国王学院", "United Kingdom"),
    (27, "University of Manchester", "曼彻斯特大学", "United Kingdom"),
    (28, "University of California, San Diego", "加州大学圣地亚哥分校", "United States"),
    (29, "University of Hong Kong", "香港大学", "Hong Kong"),
    (30, "University of Tokyo", "东京大学", "Japan"),
    (31, "Seoul National University", "首尔大学", "South Korea"),
    (32, "Kyoto University", "京都大学", "Japan"),
    (33, "Australian National University", "澳大利亚国立大学", "Australia"),
    (34, "McGill University", "麦吉尔大学", "Canada"),
    (35, "Chinese University of Hong Kong", "香港中文大学", "Hong Kong"),
    (36, "Fudan University", "复旦大学", "China"),
    (37, "Shanghai Jiao Tong University", "上海交通大学", "China"),
    (38, "Karolinska Institutet", "卡罗林斯卡学院", "Sweden"),
    (39, "University of Melbourne", "墨尔本大学", "Australia"),
    (40, "University of Sydney", "悉尼大学", "Australia"),
    (41, "University of Queensland", "昆士兰大学", "Australia"),
    (42, "City University of Hong Kong", "香港城市大学", "Hong Kong"),
    (43, "University of British Columbia", "不列颠哥伦比亚大学", "Canada"),
    (44, "Hong Kong Polytechnic University", "香港理工大学", "Hong Kong"),
    (45, "University of New South Wales", "新南威尔士大学", "Australia"),
    (46, "Brown University", "布朗大学", "United States"),
    (47, "University of Warwick", "华威大学", "United Kingdom"),
    (48, "University of Bristol", "布里斯托大学", "United Kingdom"),
    (49, "Monash University", "蒙纳士大学", "Australia"),
    (50, "University of California, Davis", "加州大学戴维斯分校", "United States"),
    (51, "Zhejiang University", "浙江大学", "China"),
    (52, "University of Amsterdam", "阿姆斯特丹大学", "Netherlands"),
    (53, "University of California, Santa Barbara", "加州大学圣塔芭芭拉分校", "United States"),
    (54, "University of Washington", "华盛顿大学", "United States"),
    (55, "University of Glasgow", "格拉斯哥大学", "United Kingdom"),
    (56, "Technical University of Munich", "慕尼黑工业大学", "Germany"),
    (57, "University of Texas at Austin", "德克萨斯大学奥斯汀分校", "United States"),
    (58, "Boston University", "波士顿大学", "United States"),
    (59, "University of Southern California", "南加州大学", "United States"),
    (60, "University of Wisconsin-Madison", "威斯康星大学麦迪逊分校", "United States"),
    (61, "University of Illinois at Urbana-Champaign", "伊利诺伊大学厄巴纳-香槟分校", "United States"),
    (62, "University of North Carolina at Chapel Hill", "北卡罗来纳大学教堂山分校", "United States"),
    (63, "Korea University", "高丽大学", "South Korea"),
    (64, "Wageningen University", "瓦赫宁根大学", "Netherlands"),
    (65, "University of Southampton", "南安普顿大学", "United Kingdom"),
    (66, "Leiden University", "莱顿大学", "Netherlands"),
    (67, "University of Sheffield", "谢菲尔德大学", "United Kingdom"),
    (68, "University of Birmingham", "伯明翰大学", "United Kingdom"),
    (69, "University of Leeds", "利兹大学", "United Kingdom"),
    (70, "University of Nottingham", "诺丁汉大学", "United Kingdom"),
    (71, "Yonsei University", "延世大学", "South Korea"),
    (72, "Pennsylvania State University", "宾夕法尼亚州立大学", "United States"),
    (73, "University of Exeter", "埃克塞特大学", "United Kingdom"),
    (74, "University of Auckland", "奥克兰大学", "New Zealand"),
    (75, "University of Western Australia", "西澳大利亚大学", "Australia"),
    (76, "University of Adelaide", "阿德莱德大学", "Australia"),
    (77, "University of Bath", "巴斯大学", "United Kingdom"),
    (78, "University of St Andrews", "圣安德鲁斯大学", "United Kingdom"),
    (79, "Hokkaido University", "北海道大学", "Japan"),
    (80, "University of Copenhagen", "哥本哈根大学", "Denmark"),
    (81, "Technical University of Denmark", "丹麦技术大学", "Denmark"),
    (82, "Uppsala University", "乌普萨拉大学", "Sweden"),
    (83, "Lund University", "隆德大学", "Sweden"),
    (84, "KTH Royal Institute of Technology", "皇家理工学院", "Sweden"),
    (85, "Trinity College Dublin", "都柏林圣三一学院", "Ireland"),
    (86, "University of Science and Technology of China", "中国科学技术大学", "China"),
    (87, "Heidelberg University", "海德堡大学", "Germany"),
    (88, "Ludwig Maximilian University of Munich", "慕尼黑大学", "Germany"),
    (89, "RWTH Aachen University", "亚琛工业大学", "Germany"),
    (90, "University of Zurich", "苏黎世大学", "Switzerland"),
    (91, "University of Basel", "巴塞尔大学", "Switzerland"),
    (92, "University of Geneva", "日内瓦大学", "Switzerland"),
    (93, "Ecole Polytechnique Federale de Lausanne", "洛桑联邦理工学院", "Switzerland"),
    (94, "Free University of Berlin", "柏林自由大学", "Germany"),
    (95, "Humboldt University of Berlin", "柏林洪堡大学", "Germany"),
    (96, "University of Vienna", "维也纳大学", "Austria"),
    (97, "University of Barcelona", "巴塞罗那大学", "Spain"),
    (98, "Osaka University", "大阪大学", "Japan"),
    (99, "Tohoku University", "东北大学", "Japan"),
    (100, "Nagoya University", "名古屋大学", "Japan"),
    (101, "National Taiwan University", "台湾大学", "Taiwan"),
    (102, "National Tsing Hua University", "清华大学", "Taiwan"),
    (103, "National Cheng Kung University", "成功大学", "Taiwan"),
    (104, "University of Malaya", "马来亚大学", "Malaysia"),
    (105, "Universiti Putra Malaysia", "马来西亚博特拉大学", "Malaysia"),
    (106, "Universiti Sains Malaysia", "马来西亚理科大学", "Malaysia"),
    (107, "Institut Teknologi Bandung", "万隆理工学院", "Indonesia"),
    (108, "University of Indonesia", "印度尼西亚大学", "Indonesia"),
    (109, "Gadjah Mada University", "加查马达大学", "Indonesia"),
    (110, "Chulalongkorn University", "朱拉隆功大学", "Thailand"),
    (111, "Mahidol University", "玛希隆大学", "Thailand"),
    (112, "Kasetsart University", "农业大学", "Thailand"),
    (113, "Chiang Mai University", "清迈大学", "Thailand"),
    (114, "Singapore Management University", "新加坡管理大学", "Singapore"),
    (115, "Singapore University of Technology and Design", "新加坡科技设计大学", "Singapore"),
    (116, "University of Macau", "澳门大学", "Macau"),
    (117, "Macau University of Science and Technology", "澳门科技大学", "Macau"),
    (118, "Hong Kong University of Science and Technology", "香港科技大学", "Hong Kong"),
    (119, "Nanjing University", "南京大学", "China"),
    (120, "Wuhan University", "武汉大学", "China"),
    (121, "Sun Yat-sen University", "中山大学", "China"),
    (122, "Harbin Institute of Technology", "哈尔滨工业大学", "China"),
    (123, "Xi'an Jiaotong University", "西安交通大学", "China"),
    (124, "Sichuan University", "四川大学", "China"),
    (125, "Tongji University", "同济大学", "China"),
    (126, "Beijing Institute of Technology", "北京理工大学", "China"),
    (127, "Southeast University", "东南大学", "China"),
    (128, "Tianjin University", "天津大学", "China"),
    (129, "Huazhong University of Science and Technology", "华中科技大学", "China"),
    (130, "Beihang University", "北京航空航天大学", "China"),
    (131, "Dalian University of Technology", "大连理工大学", "China"),
    (132, "Chongqing University", "重庆大学", "China"),
    (133, "Jilin University", "吉林大学", "China"),
    (134, "Shandong University", "山东大学", "China"),
    (135, "Nankai University", "南开大学", "China"),
    (136, "Xiamen University", "厦门大学", "China"),
    (137, "Central South University", "中南大学", "China"),
    (138, "Beijing Normal University", "北京师范大学", "China"),
    (139, "East China Normal University", "华东师范大学", "China"),
    (140, "East China University of Science and Technology", "华东理工大学", "China"),
    (141, "Northwestern Polytechnical University", "西北工业大学", "China"),
    (142, "Renmin University of China", "中国人民大学", "China"),
    (143, "Shanghai University", "上海大学", "China"),
    (144, "Soochow University", "苏州大学", "China"),
    (145, "Kunming University of Science and Technology", "昆明理工大学", "China"),
    (146, "University of Science and Technology Beijing", "北京科技大学", "China"),
    (147, "Wuhan University of Technology", "武汉理工大学", "China"),
    (148, "Hefei University of Technology", "合肥工业大学", "China"),
    (149, "Nanjing University of Science and Technology", "南京理工大学", "China"),
    (150, "Beijing Jiaotong University", "北京交通大学", "China"),
    (151, "Indian Institute of Technology Bombay", "孟买印度理工学院", "India"),
    (152, "Indian Institute of Technology Delhi", "德里印度理工学院", "India"),
    (153, "Indian Institute of Technology Madras", "马德拉斯印度理工学院", "India"),
    (154, "Indian Institute of Science", "印度科学学院", "India"),
    (155, "University of Delhi", "德里大学", "India"),
    (156, "Jawaharlal Nehru University", "贾瓦哈拉尔·尼赫鲁大学", "India"),
    (157, "All India Institute of Medical Sciences", "全印度医学科学研究所", "India"),
    (158, "Banaras Hindu University", "贝拿勒斯印度大学", "India"),
    (159, "Pohang University of Science and Technology", "浦项科技大学", "South Korea"),
    (160, "Korea Advanced Institute of Science and Technology", "韩国科学技术院", "South Korea"),
    (161, "Sungkyunkwan University", "成均馆大学", "South Korea"),
    (162, "Tokyo Institute of Technology", "东京工业大学", "Japan"),
    (163, "Waseda University", "早稻田大学", "Japan"),
    (164, "Keio University", "庆应义塾大学", "Japan"),
    (165, "Kansai University", "关西大学", "Japan"),
    (166, "Ritsumeikan University", "立命馆大学", "Japan"),
    (167, "University of Karachi", "卡拉奇大学", "Pakistan"),
    (168, "University of the Punjab", "旁遮普大学", "Pakistan"),
    (169, "National University of Sciences and Technology", "巴基斯坦国立科技大学", "Pakistan"),
    (170, "Quaid-i-Azam University", "奎德·阿扎姆大学", "Pakistan"),
    (171, "University of Colombo", "科伦坡大学", "Sri Lanka"),
    (172, "University of Dhaka", "达卡大学", "Bangladesh"),
    (173, "Bangladesh University of Engineering and Technology", "孟加拉工程技术大学", "Bangladesh"),
    (174, "Curtin University", "科廷大学", "Australia"),
    (175, "Macquarie University", "麦考瑞大学", "Australia"),
    (176, "University of Otago", "奥塔哥大学", "New Zealand"),
    (177, "RMIT University", "皇家墨尔本理工大学", "Australia"),
    (178, "University of Canberra", "堪培拉大学", "Australia"),
    (179, "Kyoto Institute of Technology", "京都工业大学", "Japan"),
    (180, "Indiana University Bloomington", "印第安纳大学伯明顿分校", "United States"),
    (181, "Carnegie Mellon University", "卡内基梅隆大学", "United States"),
    (182, "Georgia Institute of Technology", "佐治亚理工学院", "United States"),
    (183, "University of Colorado Boulder", "科罗拉多大学博尔德分校", "United States"),
    (184, "Ohio State University", "俄亥俄州立大学", "United States"),
    (185, "University of Minnesota Twin Cities", "明尼苏达大学双城分校", "United States"),
    (186, "University of Florida", "佛罗里达大学", "United States"),
    (187, "University of Pittsburgh", "匹兹堡大学", "United States"),
    (188, "McMaster University", "麦克马斯特大学", "Canada"),
    (189, "University of Waterloo", "滑铁卢大学", "Canada"),
    (190, "Western University", "韦仕敦大学", "Canada"),
    (191, "University of Alberta", "阿尔伯塔大学", "Canada"),
    (192, "University of Calgary", "卡尔加里大学", "Canada"),
    (193, "University of Ottawa", "渥太华大学", "Canada"),
    (194, "Simon Fraser University", "西蒙菲莎大学", "Canada"),
    (195, "Arizona State University", "亚利桑那州立大学", "United States"),
    (196, "University of Arizona", "亚利桑那大学", "United States"),
    (197, "University of Virginia", "弗吉尼亚大学", "United States"),
    (198, "Georgetown University", "乔治城大学", "United States"),
    (199, "Boston College", "波士顿学院", "United States"),
    (200, "Rice University", "莱斯大学", "United States"),
]

# ─────────────────────────────────────────────────────────────────────────────
# US News Best Global Universities 2026 — Top 200 (no duplicates)
# ─────────────────────────────────────────────────────────────────────────────
USNEWS_2026 = [
    (1, "Harvard University", "哈佛大学", "United States"),
    (2, "Massachusetts Institute of Technology", "麻省理工学院", "United States"),
    (3, "Stanford University", "斯坦福大学", "United States"),
    (4, "University of Oxford", "牛津大学", "United Kingdom"),
    (5, "University of Cambridge", "剑桥大学", "United Kingdom"),
    (6, "University of Pennsylvania", "宾夕法尼亚大学", "United States"),
    (7, "Johns Hopkins University", "约翰斯·霍普金斯大学", "United States"),
    (8, "Yale University", "耶鲁大学", "United States"),
    (9, "University of Chicago", "芝加哥大学", "United States"),
    (10, "Cornell University", "康奈尔大学", "United States"),
    (11, "University of California, San Francisco", "加州大学旧金山分校", "United States"),
    (12, "Princeton University", "普林斯顿大学", "United States"),
    (13, "University of California, Berkeley", "加州大学伯克利分校", "United States"),
    (14, "Columbia University", "哥伦比亚大学", "United States"),
    (15, "Duke University", "杜克大学", "United States"),
    (16, "University of California, Los Angeles", "加州大学洛杉矶分校", "United States"),
    (17, "Northwestern University", "西北大学", "United States"),
    (18, "University of Toronto", "多伦多大学", "Canada"),
    (19, "University of Michigan-Ann Arbor", "密歇根大学安娜堡分校", "United States"),
    (20, "University of Washington", "华盛顿大学", "United States"),
    (21, "Carnegie Mellon University", "卡内基梅隆大学", "United States"),
    (22, "University of California, San Diego", "加州大学圣地亚哥分校", "United States"),
    (23, "University of North Carolina at Chapel Hill", "北卡罗来纳大学教堂山分校", "United States"),
    (24, "University of Melbourne", "墨尔本大学", "Australia"),
    (25, "University of Sydney", "悉尼大学", "Australia"),
    (26, "National University of Singapore", "新加坡国立大学", "Singapore"),
    (27, "University of Texas at Austin", "德克萨斯大学奥斯汀分校", "United States"),
    (28, "University of British Columbia", "不列颠哥伦比亚大学", "Canada"),
    (29, "McGill University", "麦吉尔大学", "Canada"),
    (30, "University of Minnesota Twin Cities", "明尼苏达大学双城分校", "United States"),
    (31, "Georgia Institute of Technology", "佐治亚理工学院", "United States"),
    (32, "University of Wisconsin-Madison", "威斯康星大学麦迪逊分校", "United States"),
    (33, "University of Edinburgh", "爱丁堡大学", "United Kingdom"),
    (34, "King's College London", "伦敦国王学院", "United Kingdom"),
    (35, "University of Manchester", "曼彻斯特大学", "United Kingdom"),
    (36, "University of Hong Kong", "香港大学", "Hong Kong"),
    (37, "University of California, Davis", "加州大学戴维斯分校", "United States"),
    (38, "University of California, Santa Barbara", "加州大学圣塔芭芭拉分校", "United States"),
    (39, "Boston University", "波士顿大学", "United States"),
    (40, "University of Amsterdam", "阿姆斯特丹大学", "Netherlands"),
    (41, "University of Queensland", "昆士兰大学", "Australia"),
    (42, "University of Illinois at Urbana-Champaign", "伊利诺伊大学厄巴纳-香槟分校", "United States"),
    (43, "Ohio State University", "俄亥俄州立大学", "United States"),
    (44, "University of Florida", "佛罗里达大学", "United States"),
    (45, "University of Pittsburgh", "匹兹堡大学", "United States"),
    (46, "University of Colorado Boulder", "科罗拉多大学博尔德分校", "United States"),
    (47, "University of Southern California", "南加州大学", "United States"),
    (48, "University of Utah", "犹他大学", "United States"),
    (49, "Brown University", "布朗大学", "United States"),
    (50, "Monash University", "蒙纳士大学", "Australia"),
    (51, "University of New South Wales", "新南威尔士大学", "Australia"),
    (52, "Pennsylvania State University", "宾夕法尼亚州立大学", "United States"),
    (53, "McMaster University", "麦克马斯特大学", "Canada"),
    (54, "University of Bristol", "布里斯托大学", "United Kingdom"),
    (55, "Technical University of Munich", "慕尼黑工业大学", "Germany"),
    (56, "University of Zurich", "苏黎世大学", "Switzerland"),
    (57, "ETH Zurich", "苏黎世联邦理工学院", "Switzerland"),
    (58, "University of Tokyo", "东京大学", "Japan"),
    (59, "Imperial College London", "伦敦帝国学院", "United Kingdom"),
    (60, "Tsinghua University", "清华大学", "China"),
    (61, "Peking University", "北京大学", "China"),
    (62, "Fudan University", "复旦大学", "China"),
    (63, "Shanghai Jiao Tong University", "上海交通大学", "China"),
    (64, "Zhejiang University", "浙江大学", "China"),
    (65, "Seoul National University", "首尔大学", "South Korea"),
    (66, "Karolinska Institutet", "卡罗林斯卡学院", "Sweden"),
    (67, "Heidelberg University", "海德堡大学", "Germany"),
    (68, "Ludwig Maximilian University of Munich", "慕尼黑大学", "Germany"),
    (69, "Free University of Berlin", "柏林自由大学", "Germany"),
    (70, "Humboldt University of Berlin", "柏林洪堡大学", "Germany"),
    (71, "RWTH Aachen University", "亚琛工业大学", "Germany"),
    (72, "Technical University of Berlin", "柏林工业大学", "Germany"),
    (73, "University of Vienna", "维也纳大学", "Austria"),
    (74, "University of Copenhagen", "哥本哈根大学", "Denmark"),
    (75, "Uppsala University", "乌普萨拉大学", "Sweden"),
    (76, "Lund University", "隆德大学", "Sweden"),
    (77, "KTH Royal Institute of Technology", "皇家理工学院", "Sweden"),
    (78, "University of Oslo", "奥斯陆大学", "Norway"),
    (79, "Leiden University", "莱顿大学", "Netherlands"),
    (80, "Erasmus University Rotterdam", "鹿特丹伊拉斯谟大学", "Netherlands"),
    (81, "Utrecht University", "乌得勒支大学", "Netherlands"),
    (82, "University of Basel", "巴塞尔大学", "Switzerland"),
    (83, "University of Geneva", "日内瓦大学", "Switzerland"),
    (84, "Ecole Polytechnique Federale de Lausanne", "洛桑联邦理工学院", "Switzerland"),
    (85, "Trinity College Dublin", "都柏林圣三一学院", "Ireland"),
    (86, "University of Barcelona", "巴塞罗那大学", "Spain"),
    (87, "University of Bologna", "博洛尼亚大学", "Italy"),
    (88, "Sapienza University of Rome", "罗马第一大学", "Italy"),
    (89, "University of Padua", "帕多瓦大学", "Italy"),
    (90, "University of Milan", "米兰大学", "Italy"),
    (91, "Indiana University Bloomington", "印第安纳大学伯明顿分校", "United States"),
    (92, "University of Arizona", "亚利桑那大学", "United States"),
    (93, "Arizona State University", "亚利桑那州立大学", "United States"),
    (94, "University of Virginia", "弗吉尼亚大学", "United States"),
    (95, "University of Rochester", "罗切斯特大学", "United States"),
    (96, "University of California, Irvine", "加州大学欧文分校", "United States"),
    (97, "University of California, Santa Cruz", "加州大学圣克鲁兹分校", "United States"),
    (98, "University of Notre Dame", "圣母大学", "United States"),
    (99, "Georgetown University", "乔治城大学", "United States"),
    (100, "Washington University in St. Louis", "圣路易斯华盛顿大学", "United States"),
    (101, "Emory University", "埃默里大学", "United States"),
    (102, "Vanderbilt University", "范德堡大学", "United States"),
    (103, "Rice University", "莱斯大学", "United States"),
    (104, "Tufts University", "塔夫茨大学", "United States"),
    (105, "Boston College", "波士顿学院", "United States"),
    (106, "University of Western Ontario", "西安大略大学", "Canada"),
    (107, "University of Waterloo", "滑铁卢大学", "Canada"),
    (108, "Western University", "韦仕敦大学", "Canada"),
    (109, "Simon Fraser University", "西蒙菲莎大学", "Canada"),
    (110, "University of Calgary", "卡尔加里大学", "Canada"),
    (111, "University of Ottawa", "渥太华大学", "Canada"),
    (112, "University of Alberta", "阿尔伯塔大学", "Canada"),
    (113, "University of Queensland", "昆士兰大学", "Australia"),
    (114, "University of Sydney", "悉尼大学", "Australia"),
    (115, "University of New South Wales", "新南威尔士大学", "Australia"),
    (116, "Monash University", "蒙纳士大学", "Australia"),
    (117, "Australian National University", "澳大利亚国立大学", "Australia"),
    (118, "University of Exeter", "埃克塞特大学", "United Kingdom"),
    (119, "University of Bath", "巴斯大学", "United Kingdom"),
    (120, "University of Durham", "杜伦大学", "United Kingdom"),
    (121, "University of York", "约克大学", "United Kingdom"),
    (122, "University of St Andrews", "圣安德鲁斯大学", "United Kingdom"),
    (123, "Chinese University of Hong Kong", "香港中文大学", "Hong Kong"),
    (124, "Hong Kong University of Science and Technology", "香港科技大学", "Hong Kong"),
    (125, "Hong Kong Polytechnic University", "香港理工大学", "Hong Kong"),
    (126, "City University of Hong Kong", "香港城市大学", "Hong Kong"),
    (127, "Kyoto University", "京都大学", "Japan"),
    (128, "National Taiwan University", "台湾大学", "Taiwan"),
    (129, "Nanyang Technological University", "南洋理工大学", "Singapore"),
    (130, "University of Auckland", "奥克兰大学", "New Zealand"),
    (131, "University of Adelaide", "阿德莱德大学", "Australia"),
    (132, "Curtin University", "科廷大学", "Australia"),
    (133, "University of Warwick", "华威大学", "United Kingdom"),
    (134, "University of Glasgow", "格拉斯哥大学", "United Kingdom"),
    (135, "University of Southampton", "南安普顿大学", "United Kingdom"),
    (136, "University of Leeds", "利兹大学", "United Kingdom"),
    (137, "University of Sheffield", "谢菲尔德大学", "United Kingdom"),
    (138, "University of Nottingham", "诺丁汉大学", "United Kingdom"),
    (139, "Nanjing University", "南京大学", "China"),
    (140, "Wuhan University", "武汉大学", "China"),
    (141, "Sun Yat-sen University", "中山大学", "China"),
    (142, "Harbin Institute of Technology", "哈尔滨工业大学", "China"),
    (143, "Xi'an Jiaotong University", "西安交通大学", "China"),
    (144, "Tongji University", "同济大学", "China"),
    (145, "Beijing Institute of Technology", "北京理工大学", "China"),
    (146, "Southeast University", "东南大学", "China"),
    (147, "Tianjin University", "天津大学", "China"),
    (148, "Huazhong University of Science and Technology", "华中科技大学", "China"),
    (149, "Sichuan University", "四川大学", "China"),
    (150, "Beihang University", "北京航空航天大学", "China"),
    (151, "Korea University", "高丽大学", "South Korea"),
    (152, "Yonsei University", "延世大学", "South Korea"),
    (153, "Korea Advanced Institute of Science and Technology", "韩国科学技术院", "South Korea"),
    (154, "Pohang University of Science and Technology", "浦项科技大学", "South Korea"),
    (155, "Sungkyunkwan University", "成均馆大学", "South Korea"),
    (156, "Osaka University", "大阪大学", "Japan"),
    (157, "Tohoku University", "东北大学", "Japan"),
    (158, "Hokkaido University", "北海道大学", "Japan"),
    (159, "Nagoya University", "名古屋大学", "Japan"),
    (160, "Tokyo Institute of Technology", "东京工业大学", "Japan"),
    (161, "Waseda University", "早稻田大学", "Japan"),
    (162, "Keio University", "庆应义塾大学", "Japan"),
    (163, "Indian Institute of Technology Bombay", "孟买印度理工学院", "India"),
    (164, "Indian Institute of Technology Delhi", "德里印度理工学院", "India"),
    (165, "Indian Institute of Technology Madras", "马德拉斯印度理工学院", "India"),
    (166, "Indian Institute of Science", "印度科学学院", "India"),
    (167, "University of Delhi", "德里大学", "India"),
    (168, "University of Malaya", "马来亚大学", "Malaysia"),
    (169, "Chulalongkorn University", "朱拉隆功大学", "Thailand"),
    (170, "Mahidol University", "玛希隆大学", "Thailand"),
    (171, "University of the Philippines", "菲律宾大学", "Philippines"),
    (172, "University of Colombo", "科伦坡大学", "Sri Lanka"),
    (173, "University of Dhaka", "达卡大学", "Bangladesh"),
    (174, "Institut Teknologi Bandung", "万隆理工学院", "Indonesia"),
    (175, "University of Indonesia", "印度尼西亚大学", "Indonesia"),
    (176, "Gadjah Mada University", "加查马达大学", "Indonesia"),
    (177, "University of Macau", "澳门大学", "Macau"),
    (178, "National Cheng Kung University", "成功大学", "Taiwan"),
    (179, "National Tsing Hua University", "清华大学", "Taiwan"),
    (180, "University of Ljubljana", "卢布尔雅那大学", "Slovenia"),
    (181, "University of Belgrade", "贝尔格莱德大学", "Serbia"),
    (182, "University of Warsaw", "华沙大学", "Poland"),
    (183, "Jagiellonian University", "雅盖隆大学", "Poland"),
    (184, "University of Bucharest", "布加勒斯特大学", "Romania"),
    (185, "Charles University", "查理大学", "Czech Republic"),
    (186, "Eotvos Lorand University", "罗兰大学", "Hungary"),
    (187, "University of Helsinki", "赫尔辛基大学", "Finland"),
    (188, "Stevens Institute of Technology", "史蒂文斯理工学院", "United States"),
    (189, "Dartmouth College", "达特茅斯学院", "United States"),
    (190, "University of St Gallen", "圣加仑大学", "Switzerland"),
    (191, "Bocconi University", "博科尼大学", "Italy"),
    (192, "IE University", "IE大学", "Spain"),
    (193, "ESSEC Business School", "ESSEC高等商学院", "France"),
    (194, "HEC Paris", "巴黎高等商学院", "France"),
    (195, "Delft University of Technology", "代尔夫特理工大学", "Netherlands"),
    (196, "Politecnico di Milano", "米兰理工大学", "Italy"),
    (197, "Technical University of Denmark", "丹麦技术大学", "Denmark"),
    (198, "Ecole Polytechnique", "巴黎综合理工学院", "France"),
    (199, "Indian Institute of Technology Kharagpur", "印度理工学院卡拉格普尔分校", "India"),
    (200, "Tsinghua University", "清华大学", "China"),
]

# ─────────────────────────────────────────────────────────────────────────────
# Times Higher Education (THE) World University Rankings 2026 — Top 200
# ─────────────────────────────────────────────────────────────────────────────
THE_2026 = [
    (1, "University of Oxford", "牛津大学", "United Kingdom"),
    (2, "Harvard University", "哈佛大学", "United States"),
    (3, "University of Cambridge", "剑桥大学", "United Kingdom"),
    (4, "Princeton University", "普林斯顿大学", "United States"),
    (5, "Stanford University", "斯坦福大学", "United States"),
    (6, "Massachusetts Institute of Technology", "麻省理工学院", "United States"),
    (7, "Imperial College London", "伦敦帝国学院", "United Kingdom"),
    (8, "University of California, Berkeley", "加州大学伯克利分校", "United States"),
    (9, "Yale University", "耶鲁大学", "United States"),
    (10, "University of Chicago", "芝加哥大学", "United States"),
    (11, "Columbia University", "哥伦比亚大学", "United States"),
    (12, "University of Pennsylvania", "宾夕法尼亚大学", "United States"),
    (13, "Johns Hopkins University", "约翰斯·霍普金斯大学", "United States"),
    (14, "Cornell University", "康奈尔大学", "United States"),
    (15, "University of California, Los Angeles", "加州大学洛杉矶分校", "United States"),
    (16, "Duke University", "杜克大学", "United States"),
    (17, "Northwestern University", "西北大学", "United States"),
    (18, "University of Michigan-Ann Arbor", "密歇根大学安娜堡分校", "United States"),
    (19, "University of Toronto", "多伦多大学", "Canada"),
    (20, "University of Edinburgh", "爱丁堡大学", "United Kingdom"),
    (21, "University of California, San Diego", "加州大学圣地亚哥分校", "United States"),
    (22, "University of Washington", "华盛顿大学", "United States"),
    (23, "King's College London", "伦敦国王学院", "United Kingdom"),
    (24, "University of Manchester", "曼彻斯特大学", "United Kingdom"),
    (25, "University of Melbourne", "墨尔本大学", "Australia"),
    (26, "University of Queensland", "昆士兰大学", "Australia"),
    (27, "University of Sydney", "悉尼大学", "Australia"),
    (28, "University of Hong Kong", "香港大学", "Hong Kong"),
    (29, "University of Tokyo", "东京大学", "Japan"),
    (30, "Seoul National University", "首尔大学", "South Korea"),
    (31, "National University of Singapore", "新加坡国立大学", "Singapore"),
    (32, "University of California, Santa Barbara", "加州大学圣塔芭芭拉分校", "United States"),
    (33, "University of North Carolina at Chapel Hill", "北卡罗来纳大学教堂山分校", "United States"),
    (34, "University of Wisconsin-Madison", "威斯康星大学麦迪逊分校", "United States"),
    (35, "University of Illinois at Urbana-Champaign", "伊利诺伊大学厄巴纳-香槟分校", "United States"),
    (36, "McGill University", "麦吉尔大学", "Canada"),
    (37, "Tsinghua University", "清华大学", "China"),
    (38, "Peking University", "北京大学", "China"),
    (39, "ETH Zurich", "苏黎世联邦理工学院", "Switzerland"),
    (40, "University of British Columbia", "不列颠哥伦比亚大学", "Canada"),
    (41, "University of New South Wales", "新南威尔士大学", "Australia"),
    (42, "Monash University", "蒙纳士大学", "Australia"),
    (43, "University of Amsterdam", "阿姆斯特丹大学", "Netherlands"),
    (44, "University of Texas at Austin", "德克萨斯大学奥斯汀分校", "United States"),
    (45, "University of Southern California", "南加州大学", "United States"),
    (46, "Boston University", "波士顿大学", "United States"),
    (47, "Brown University", "布朗大学", "United States"),
    (48, "University of California, Davis", "加州大学戴维斯分校", "United States"),
    (49, "Technical University of Munich", "慕尼黑工业大学", "Germany"),
    (50, "Karolinska Institutet", "卡罗林斯卡学院", "Sweden"),
    (51, "Kyoto University", "京都大学", "Japan"),
    (52, "Heidelberg University", "海德堡大学", "Germany"),
    (53, "Fudan University", "复旦大学", "China"),
    (54, "Shanghai Jiao Tong University", "上海交通大学", "China"),
    (55, "Nanyang Technological University", "南洋理工大学", "Singapore"),
    (56, "Chinese University of Hong Kong", "香港中文大学", "Hong Kong"),
    (57, "University of Bristol", "布里斯托大学", "United Kingdom"),
    (58, "University of Warwick", "华威大学", "United Kingdom"),
    (59, "University of Southampton", "南安普顿大学", "United Kingdom"),
    (60, "University of Glasgow", "格拉斯哥大学", "United Kingdom"),
    (61, "University of Leeds", "利兹大学", "United Kingdom"),
    (62, "University of Sheffield", "谢菲尔德大学", "United Kingdom"),
    (63, "University of Nottingham", "诺丁汉大学", "United Kingdom"),
    (64, "University of Birmingham", "伯明翰大学", "United Kingdom"),
    (65, "University of York", "约克大学", "United Kingdom"),
    (66, "University of Exeter", "埃克塞特大学", "United Kingdom"),
    (67, "University of Durham", "杜伦大学", "United Kingdom"),
    (68, "University of Bath", "巴斯大学", "United Kingdom"),
    (69, "University of St Andrews", "圣安德鲁斯大学", "United Kingdom"),
    (70, "Leiden University", "莱顿大学", "Netherlands"),
    (71, "Utrecht University", "乌得勒支大学", "Netherlands"),
    (72, "Erasmus University Rotterdam", "鹿特丹伊拉斯谟大学", "Netherlands"),
    (73, "Free University of Berlin", "柏林自由大学", "Germany"),
    (74, "Humboldt University of Berlin", "柏林洪堡大学", "Germany"),
    (75, "Ludwig Maximilian University of Munich", "慕尼黑大学", "Germany"),
    (76, "RWTH Aachen University", "亚琛工业大学", "Germany"),
    (77, "Technical University of Berlin", "柏林工业大学", "Germany"),
    (78, "University of Vienna", "维也纳大学", "Austria"),
    (79, "University of Zurich", "苏黎世大学", "Switzerland"),
    (80, "University of Basel", "巴塞尔大学", "Switzerland"),
    (81, "University of Geneva", "日内瓦大学", "Switzerland"),
    (82, "Ecole Polytechnique Federale de Lausanne", "洛桑联邦理工学院", "Switzerland"),
    (83, "Uppsala University", "乌普萨拉大学", "Sweden"),
    (84, "Lund University", "隆德大学", "Sweden"),
    (85, "KTH Royal Institute of Technology", "皇家理工学院", "Sweden"),
    (86, "University of Copenhagen", "哥本哈根大学", "Denmark"),
    (87, "Technical University of Denmark", "丹麦技术大学", "Denmark"),
    (88, "University of Oslo", "奥斯陆大学", "Norway"),
    (89, "Trinity College Dublin", "都柏林圣三一学院", "Ireland"),
    (90, "University of Barcelona", "巴塞罗那大学", "Spain"),
    (91, "University of Bologna", "博洛尼亚大学", "Italy"),
    (92, "University of Padua", "帕多瓦大学", "Italy"),
    (93, "Sapienza University of Rome", "罗马第一大学", "Italy"),
    (94, "University of Milan", "米兰大学", "Italy"),
    (95, "National Taiwan University", "台湾大学", "Taiwan"),
    (96, "Hong Kong Polytechnic University", "香港理工大学", "Hong Kong"),
    (97, "Hong Kong University of Science and Technology", "香港科技大学", "Hong Kong"),
    (98, "City University of Hong Kong", "香港城市大学", "Hong Kong"),
    (99, "University of Auckland", "奥克兰大学", "New Zealand"),
    (100, "Australian National University", "澳大利亚国立大学", "Australia"),
    (101, "University of Adelaide", "阿德莱德大学", "Australia"),
    (102, "University of Western Australia", "西澳大利亚大学", "Australia"),
    (103, "Korea University", "高丽大学", "South Korea"),
    (104, "Yonsei University", "延世大学", "South Korea"),
    (105, "Korea Advanced Institute of Science and Technology", "韩国科学技术院", "South Korea"),
    (106, "Pohang University of Science and Technology", "浦项科技大学", "South Korea"),
    (107, "Sungkyunkwan University", "成均馆大学", "South Korea"),
    (108, "Osaka University", "大阪大学", "Japan"),
    (109, "Tohoku University", "东北大学", "Japan"),
    (110, "Hokkaido University", "北海道大学", "Japan"),
    (111, "Nagoya University", "名古屋大学", "Japan"),
    (112, "Tokyo Institute of Technology", "东京工业大学", "Japan"),
    (113, "Waseda University", "早稻田大学", "Japan"),
    (114, "Keio University", "庆应义塾大学", "Japan"),
    (115, "Zhejiang University", "浙江大学", "China"),
    (116, "Nanjing University", "南京大学", "China"),
    (117, "Wuhan University", "武汉大学", "China"),
    (118, "Sun Yat-sen University", "中山大学", "China"),
    (119, "Harbin Institute of Technology", "哈尔滨工业大学", "China"),
    (120, "Xi'an Jiaotong University", "西安交通大学", "China"),
    (121, "University of Science and Technology of China", "中国科学技术大学", "China"),
    (122, "Tongji University", "同济大学", "China"),
    (123, "Beijing Institute of Technology", "北京理工大学", "China"),
    (124, "Southeast University", "东南大学", "China"),
    (125, "Tianjin University", "天津大学", "China"),
    (126, "Huazhong University of Science and Technology", "华中科技大学", "China"),
    (127, "Sichuan University", "四川大学", "China"),
    (128, "Beihang University", "北京航空航天大学", "China"),
    (129, "Dalian University of Technology", "大连理工大学", "China"),
    (130, "Chongqing University", "重庆大学", "China"),
    (131, "Indian Institute of Technology Bombay", "孟买印度理工学院", "India"),
    (132, "Indian Institute of Technology Delhi", "德里印度理工学院", "India"),
    (133, "Indian Institute of Science", "印度科学学院", "India"),
    (134, "University of Delhi", "德里大学", "India"),
    (135, "University of Malaya", "马来亚大学", "Malaysia"),
    (136, "Chulalongkorn University", "朱拉隆功大学", "Thailand"),
    (137, "Mahidol University", "玛希隆大学", "Thailand"),
    (138, "Institut Teknologi Bandung", "万隆理工学院", "Indonesia"),
    (139, "University of Indonesia", "印度尼西亚大学", "Indonesia"),
    (140, "University of the Philippines", "菲律宾大学", "Philippines"),
    (141, "University of Colombo", "科伦坡大学", "Sri Lanka"),
    (142, "University of Dhaka", "达卡大学", "Bangladesh"),
    (143, "McMaster University", "麦克马斯特大学", "Canada"),
    (144, "University of Waterloo", "滑铁卢大学", "Canada"),
    (145, "Western University", "韦仕敦大学", "Canada"),
    (146, "University of Alberta", "阿尔伯塔大学", "Canada"),
    (147, "University of Calgary", "卡尔加里大学", "Canada"),
    (148, "University of Ottawa", "渥太华大学", "Canada"),
    (149, "Indiana University Bloomington", "印第安纳大学伯明顿分校", "United States"),
    (150, "University of Arizona", "亚利桑那大学", "United States"),
    (151, "Arizona State University", "亚利桑那州立大学", "United States"),
    (152, "University of Colorado Boulder", "科罗拉多大学博尔德分校", "United States"),
    (153, "Ohio State University", "俄亥俄州立大学", "United States"),
    (154, "Pennsylvania State University", "宾夕法尼亚州立大学", "United States"),
    (155, "University of Florida", "佛罗里达大学", "United States"),
    (156, "University of Pittsburgh", "匹兹堡大学", "United States"),
    (157, "University of Minnesota Twin Cities", "明尼苏达大学双城分校", "United States"),
    (158, "University of Utah", "犹他大学", "United States"),
    (159, "University of Virginia", "弗吉尼亚大学", "United States"),
    (160, "Georgetown University", "乔治城大学", "United States"),
    (161, "Emory University", "埃默里大学", "United States"),
    (162, "Vanderbilt University", "范德堡大学", "United States"),
    (163, "Rice University", "莱斯大学", "United States"),
    (164, "University of Rochester", "罗切斯特大学", "United States"),
    (165, "Washington University in St. Louis", "圣路易斯华盛顿大学", "United States"),
    (166, "University of California, Irvine", "加州大学欧文分校", "United States"),
    (167, "University of California, Santa Cruz", "加州大学圣克鲁兹分校", "United States"),
    (168, "University of Notre Dame", "圣母大学", "United States"),
    (169, "Tufts University", "塔夫茨大学", "United States"),
    (170, "Boston College", "波士顿学院", "United States"),
    (171, "University of Macau", "澳门大学", "Macau"),
    (172, "National Cheng Kung University", "成功大学", "Taiwan"),
    (173, "National Tsing Hua University", "清华大学", "Taiwan"),
    (174, "University of Warsaw", "华沙大学", "Poland"),
    (175, "Jagiellonian University", "雅盖隆大学", "Poland"),
    (176, "University of Belgrade", "贝尔格莱德大学", "Serbia"),
    (177, "University of Ljubljana", "卢布尔雅那大学", "Slovenia"),
    (178, "University of Bucharest", "布加勒斯特大学", "Romania"),
    (179, "Charles University", "查理大学", "Czech Republic"),
    (180, "Eotvos Lorand University", "罗兰大学", "Hungary"),
    (181, "University of Helsinki", "赫尔辛基大学", "Finland"),
    (182, "University of Cape Town", "开普敦大学", "South Africa"),
    (183, "University of Witwatersrand", "金山大学", "South Africa"),
    (184, "Stellenbosch University", "斯泰伦博斯大学", "South Africa"),
    (185, "University of Pretoria", "比勒陀利亚大学", "South Africa"),
    (186, "American University of Beirut", "贝鲁特美国大学", "Lebanon"),
    (187, "University of Haifa", "海法大学", "Israel"),
    (188, "Hebrew University of Jerusalem", "耶路撒冷希伯来大学", "Israel"),
    (189, "Technion Israel Institute of Technology", "以色列理工学院", "Israel"),
    (190, "Tel Aviv University", "特拉维夫大学", "Israel"),
    (191, "American University in Cairo", "开罗美国大学", "Egypt"),
    (192, "Bogazici University", "海峡大学", "Turkey"),
    (193, "Koç University", "科奇大学", "Turkey"),
    (194, "University of Karachi", "卡拉奇大学", "Pakistan"),
    (195, "Quaid-i-Azam University", "奎德·阿扎姆大学", "Pakistan"),
    (196, "National University of Sciences and Technology", "巴基斯坦国立科技大学", "Pakistan"),
    (197, "Bangladesh University of Engineering and Technology", "孟加拉工程技术大学", "Bangladesh"),
    (198, "Asian Institute of Technology", "亚洲理工大学", "Thailand"),
    (199, "National Taiwan University of Science and Technology", "台湾科技大学", "Taiwan"),
    (200, "University of Malaya", "马来亚大学", "Malaysia"),
]

# ─────────────────────────────────────────────────────────────────────────────
# ARWU (Shanghai Ranking) 2025 — Top 200 (no duplicates)
# ─────────────────────────────────────────────────────────────────────────────
ARWU_2025 = [
    (1, "Harvard University", "哈佛大学", "United States"),
    (2, "Stanford University", "斯坦福大学", "United States"),
    (3, "Massachusetts Institute of Technology", "麻省理工学院", "United States"),
    (4, "University of Cambridge", "剑桥大学", "United Kingdom"),
    (5, "University of California, Berkeley", "加州大学伯克利分校", "United States"),
    (6, "Princeton University", "普林斯顿大学", "United States"),
    (7, "University of Oxford", "牛津大学", "United Kingdom"),
    (8, "Columbia University", "哥伦比亚大学", "United States"),
    (9, "California Institute of Technology", "加州理工学院", "United States"),
    (10, "University of Chicago", "芝加哥大学", "United States"),
    (11, "Yale University", "耶鲁大学", "United States"),
    (12, "University of Pennsylvania", "宾夕法尼亚大学", "United States"),
    (13, "Johns Hopkins University", "约翰斯·霍普金斯大学", "United States"),
    (14, "University of California, Los Angeles", "加州大学洛杉矶分校", "United States"),
    (15, "Cornell University", "康奈尔大学", "United States"),
    (16, "University of Michigan-Ann Arbor", "密歇根大学安娜堡分校", "United States"),
    (17, "University of California, San Diego", "加州大学圣地亚哥分校", "United States"),
    (18, "University of Toronto", "多伦多大学", "Canada"),
    (19, "University of Washington", "华盛顿大学", "United States"),
    (20, "Northwestern University", "西北大学", "United States"),
    (21, "University of North Carolina at Chapel Hill", "北卡罗来纳大学教堂山分校", "United States"),
    (22, "Duke University", "杜克大学", "United States"),
    (23, "University of California, San Francisco", "加州大学旧金山分校", "United States"),
    (24, "University of Wisconsin-Madison", "威斯康星大学麦迪逊分校", "United States"),
    (25, "University of Illinois at Urbana-Champaign", "伊利诺伊大学厄巴纳-香槟分校", "United States"),
    (26, "University of Edinburgh", "爱丁堡大学", "United Kingdom"),
    (27, "University of California, Santa Barbara", "加州大学圣塔芭芭拉分校", "United States"),
    (28, "University of Texas at Austin", "德克萨斯大学奥斯汀分校", "United States"),
    (29, "University of British Columbia", "不列颠哥伦比亚大学", "Canada"),
    (30, "University of Melbourne", "墨尔本大学", "Australia"),
    (31, "University of Sydney", "悉尼大学", "Australia"),
    (32, "University of Manchester", "曼彻斯特大学", "United Kingdom"),
    (33, "McGill University", "麦吉尔大学", "Canada"),
    (34, "University of Tokyo", "东京大学", "Japan"),
    (35, "Kyoto University", "京都大学", "Japan"),
    (36, "Seoul National University", "首尔大学", "South Korea"),
    (37, "University of Hong Kong", "香港大学", "Hong Kong"),
    (38, "University of Queensland", "昆士兰大学", "Australia"),
    (39, "National University of Singapore", "新加坡国立大学", "Singapore"),
    (40, "University of New South Wales", "新南威尔士大学", "Australia"),
    (41, "King's College London", "伦敦国王学院", "United Kingdom"),
    (42, "Carnegie Mellon University", "卡内基梅隆大学", "United States"),
    (43, "Brown University", "布朗大学", "United States"),
    (44, "Boston University", "波士顿大学", "United States"),
    (45, "Georgia Institute of Technology", "佐治亚理工学院", "United States"),
    (46, "University of Western Australia", "西澳大利亚大学", "Australia"),
    (47, "University of Amsterdam", "阿姆斯特丹大学", "Netherlands"),
    (48, "University of Bristol", "布里斯托大学", "United Kingdom"),
    (49, "University of Glasgow", "格拉斯哥大学", "United Kingdom"),
    (50, "University of Warwick", "华威大学", "United Kingdom"),
    (51, "Technical University of Munich", "慕尼黑工业大学", "Germany"),
    (52, "Ludwig Maximilian University of Munich", "慕尼黑大学", "Germany"),
    (53, "ETH Zurich", "苏黎世联邦理工学院", "Switzerland"),
    (54, "Heidelberg University", "海德堡大学", "Germany"),
    (55, "University of Zurich", "苏黎世大学", "Switzerland"),
    (56, "Free University of Berlin", "柏林自由大学", "Germany"),
    (57, "Humboldt University of Berlin", "柏林洪堡大学", "Germany"),
    (58, "RWTH Aachen University", "亚琛工业大学", "Germany"),
    (59, "Fudan University", "复旦大学", "China"),
    (60, "Tsinghua University", "清华大学", "China"),
    (61, "Peking University", "北京大学", "China"),
    (62, "Shanghai Jiao Tong University", "上海交通大学", "China"),
    (63, "Zhejiang University", "浙江大学", "China"),
    (64, "Nanjing University", "南京大学", "China"),
    (65, "Chinese University of Hong Kong", "香港中文大学", "Hong Kong"),
    (66, "University of Science and Technology of China", "中国科学技术大学", "China"),
    (67, "Nanyang Technological University", "南洋理工大学", "Singapore"),
    (68, "Hong Kong University of Science and Technology", "香港科技大学", "Hong Kong"),
    (69, "Hong Kong Polytechnic University", "香港理工大学", "Hong Kong"),
    (70, "City University of Hong Kong", "香港城市大学", "Hong Kong"),
    (71, "Karolinska Institutet", "卡罗林斯卡学院", "Sweden"),
    (72, "Uppsala University", "乌普萨拉大学", "Sweden"),
    (73, "Lund University", "隆德大学", "Sweden"),
    (74, "KTH Royal Institute of Technology", "皇家理工学院", "Sweden"),
    (75, "University of Copenhagen", "哥本哈根大学", "Denmark"),
    (76, "Monash University", "蒙纳士大学", "Australia"),
    (77, "Australian National University", "澳大利亚国立大学", "Australia"),
    (78, "University of Southampton", "南安普顿大学", "United Kingdom"),
    (79, "University of Leeds", "利兹大学", "United Kingdom"),
    (80, "University of Sheffield", "谢菲尔德大学", "United Kingdom"),
    (81, "University of Birmingham", "伯明翰大学", "United Kingdom"),
    (82, "University of Nottingham", "诺丁汉大学", "United Kingdom"),
    (83, "University of Liverpool", "利物浦大学", "United Kingdom"),
    (84, "Leiden University", "莱顿大学", "Netherlands"),
    (85, "Utrecht University", "乌得勒支大学", "Netherlands"),
    (86, "Erasmus University Rotterdam", "鹿特丹伊拉斯谟大学", "Netherlands"),
    (87, "Wageningen University", "瓦赫宁根大学", "Netherlands"),
    (88, "University of Vienna", "维也纳大学", "Austria"),
    (89, "Trinity College Dublin", "都柏林圣三一学院", "Ireland"),
    (90, "University of Barcelona", "巴塞罗那大学", "Spain"),
    (91, "University of Bologna", "博洛尼亚大学", "Italy"),
    (92, "Sapienza University of Rome", "罗马第一大学", "Italy"),
    (93, "University of Padua", "帕多瓦大学", "Italy"),
    (94, "University of Milan", "米兰大学", "Italy"),
    (95, "University of Geneva", "日内瓦大学", "Switzerland"),
    (96, "University of Basel", "巴塞尔大学", "Switzerland"),
    (97, "McMaster University", "麦克马斯特大学", "Canada"),
    (98, "University of Alberta", "阿尔伯塔大学", "Canada"),
    (99, "Indiana University Bloomington", "印第安纳大学伯明顿分校", "United States"),
    (100, "University of Minnesota Twin Cities", "明尼苏达大学双城分校", "United States"),
    (101, "Ohio State University", "俄亥俄州立大学", "United States"),
    (102, "Pennsylvania State University", "宾夕法尼亚州立大学", "United States"),
    (103, "University of Colorado Boulder", "科罗拉多大学博尔德分校", "United States"),
    (104, "University of Florida", "佛罗里达大学", "United States"),
    (105, "University of Pittsburgh", "匹兹堡大学", "United States"),
    (106, "Purdue University", "普渡大学", "United States"),
    (107, "University of Southern California", "南加州大学", "United States"),
    (108, "Washington University in St. Louis", "圣路易斯华盛顿大学", "United States"),
    (109, "Vanderbilt University", "范德堡大学", "United States"),
    (110, "Emory University", "埃默里大学", "United States"),
    (111, "University of Rochester", "罗切斯特大学", "United States"),
    (112, "University of California, Davis", "加州大学戴维斯分校", "United States"),
    (113, "University of California, Irvine", "加州大学欧文分校", "United States"),
    (114, "University of California, Santa Cruz", "加州大学圣克鲁兹分校", "United States"),
    (115, "University of Arizona", "亚利桑那大学", "United States"),
    (116, "Arizona State University", "亚利桑那州立大学", "United States"),
    (117, "University of Virginia", "弗吉尼亚大学", "United States"),
    (118, "Georgetown University", "乔治城大学", "United States"),
    (119, "University of Notre Dame", "圣母大学", "United States"),
    (120, "Rice University", "莱斯大学", "United States"),
    (121, "Tufts University", "塔夫茨大学", "United States"),
    (122, "Boston College", "波士顿学院", "United States"),
    (123, "Osaka University", "大阪大学", "Japan"),
    (124, "Tohoku University", "东北大学", "Japan"),
    (125, "Hokkaido University", "北海道大学", "Japan"),
    (126, "Nagoya University", "名古屋大学", "Japan"),
    (127, "Kyoto Institute of Technology", "京都工业大学", "Japan"),
    (128, "Tokyo Institute of Technology", "东京工业大学", "Japan"),
    (129, "Korea University", "高丽大学", "South Korea"),
    (130, "Yonsei University", "延世大学", "South Korea"),
    (131, "Korea Advanced Institute of Science and Technology", "韩国科学技术院", "South Korea"),
    (132, "Pohang University of Science and Technology", "浦项科技大学", "South Korea"),
    (133, "Sungkyunkwan University", "成均馆大学", "South Korea"),
    (134, "National Taiwan University", "台湾大学", "Taiwan"),
    (135, "National Tsing Hua University", "清华大学", "Taiwan"),
    (136, "National Cheng Kung University", "成功大学", "Taiwan"),
    (137, "Indian Institute of Technology Bombay", "孟买印度理工学院", "India"),
    (138, "Indian Institute of Technology Delhi", "德里印度理工学院", "India"),
    (139, "Indian Institute of Technology Madras", "马德拉斯印度理工学院", "India"),
    (140, "Indian Institute of Science", "印度科学学院", "India"),
    (141, "University of Delhi", "德里大学", "India"),
    (142, "University of Malaya", "马来亚大学", "Malaysia"),
    (143, "Chulalongkorn University", "朱拉隆功大学", "Thailand"),
    (144, "Mahidol University", "玛希隆大学", "Thailand"),
    (145, "Institut Teknologi Bandung", "万隆理工学院", "Indonesia"),
    (146, "University of Indonesia", "印度尼西亚大学", "Indonesia"),
    (147, "Wuhan University", "武汉大学", "China"),
    (148, "Sun Yat-sen University", "中山大学", "China"),
    (149, "Harbin Institute of Technology", "哈尔滨工业大学", "China"),
    (150, "Xi'an Jiaotong University", "西安交通大学", "China"),
    (151, "Tongji University", "同济大学", "China"),
    (152, "Beijing Institute of Technology", "北京理工大学", "China"),
    (153, "Southeast University", "东南大学", "China"),
    (154, "Tianjin University", "天津大学", "China"),
    (155, "Huazhong University of Science and Technology", "华中科技大学", "China"),
    (156, "Sichuan University", "四川大学", "China"),
    (157, "Beihang University", "北京航空航天大学", "China"),
    (158, "Dalian University of Technology", "大连理工大学", "China"),
    (159, "Chongqing University", "重庆大学", "China"),
    (160, "Jilin University", "吉林大学", "China"),
    (161, "Shandong University", "山东大学", "China"),
    (162, "Nankai University", "南开大学", "China"),
    (163, "Xiamen University", "厦门大学", "China"),
    (164, "Central South University", "中南大学", "China"),
    (165, "East China Normal University", "华东师范大学", "China"),
    (166, "Beijing Normal University", "北京师范大学", "China"),
    (167, "University of Auckland", "奥克兰大学", "New Zealand"),
    (168, "University of Otago", "奥塔哥大学", "New Zealand"),
    (169, "Curtin University", "科廷大学", "Australia"),
    (170, "University of Adelaide", "阿德莱德大学", "Australia"),
    (171, "RMIT University", "皇家墨尔本理工大学", "Australia"),
    (172, "Macquarie University", "麦考瑞大学", "Australia"),
    (173, "University of Exeter", "埃克塞特大学", "United Kingdom"),
    (174, "University of Durham", "杜伦大学", "United Kingdom"),
    (175, "University of Bath", "巴斯大学", "United Kingdom"),
    (176, "University of St Andrews", "圣安德鲁斯大学", "United Kingdom"),
    (177, "Technical University of Berlin", "柏林工业大学", "Germany"),
    (178, "University of Hamburg", "汉堡大学", "Germany"),
    (179, "University of Cologne", "科隆大学", "Germany"),
    (180, "University of Frankfurt", "法兰克福大学", "Germany"),
    (181, "University of Bonn", "波恩大学", "Germany"),
    (182, "University of Munich", "慕尼黑大学", "Germany"),
    (183, "University of Goettingen", "哥廷根大学", "Germany"),
    (184, "University of Tuebingen", "蒂宾根大学", "Germany"),
    (185, "University of Freiburg", "弗赖堡大学", "Germany"),
    (186, "Stockholm University", "斯德哥尔摩大学", "Sweden"),
    (187, "University of Helsinki", "赫尔辛基大学", "Finland"),
    (188, "University of Oslo", "奥斯陆大学", "Norway"),
    (189, "Aarhus University", "奥胡斯大学", "Denmark"),
    (190, "University of Warsaw", "华沙大学", "Poland"),
    (191, "Jagiellonian University", "雅盖隆大学", "Poland"),
    (192, "Charles University", "查理大学", "Czech Republic"),
    (193, "University of Belgrade", "贝尔格莱德大学", "Serbia"),
    (194, "University of Ljubljana", "卢布尔雅那大学", "Slovenia"),
    (195, "University of Cape Town", "开普敦大学", "South Africa"),
    (196, "University of Witwatersrand", "金山大学", "South Africa"),
    (197, "Stellenbosch University", "斯泰伦博斯大学", "South Africa"),
    (198, "University of Pretoria", "比勒陀利亚大学", "South Africa"),
    (199, "University of Istanbul", "伊斯坦布尔大学", "Turkey"),
    (200, "University of Buenos Aires", "布宜诺斯艾利斯大学", "Argentina"),
]

# ─────────────────────────────────────────────────────────────────────────────
# CWUR World University Rankings 2025 — Top 200 (no duplicates)
# ─────────────────────────────────────────────────────────────────────────────
CWUR_2025 = [
    (1, "Harvard University", "哈佛大学", "United States"),
    (2, "Massachusetts Institute of Technology", "麻省理工学院", "United States"),
    (3, "Stanford University", "斯坦福大学", "United States"),
    (4, "University of Cambridge", "剑桥大学", "United Kingdom"),
    (5, "University of Oxford", "牛津大学", "United Kingdom"),
    (6, "Columbia University", "哥伦比亚大学", "United States"),
    (7, "University of Chicago", "芝加哥大学", "United States"),
    (8, "Yale University", "耶鲁大学", "United States"),
    (9, "University of Pennsylvania", "宾夕法尼亚大学", "United States"),
    (10, "Princeton University", "普林斯顿大学", "United States"),
    (11, "Cornell University", "康奈尔大学", "United States"),
    (12, "Johns Hopkins University", "约翰斯·霍普金斯大学", "United States"),
    (13, "University of California, Berkeley", "加州大学伯克利分校", "United States"),
    (14, "University of California, Los Angeles", "加州大学洛杉矶分校", "United States"),
    (15, "Duke University", "杜克大学", "United States"),
    (16, "Northwestern University", "西北大学", "United States"),
    (17, "University of California, San Diego", "加州大学圣地亚哥分校", "United States"),
    (18, "University of Toronto", "多伦多大学", "Canada"),
    (19, "University of Michigan-Ann Arbor", "密歇根大学安娜堡分校", "United States"),
    (20, "University of Washington", "华盛顿大学", "United States"),
    (21, "University of North Carolina at Chapel Hill", "北卡罗来纳大学教堂山分校", "United States"),
    (22, "Carnegie Mellon University", "卡内基梅隆大学", "United States"),
    (23, "University of California, San Francisco", "加州大学旧金山分校", "United States"),
    (24, "Georgia Institute of Technology", "佐治亚理工学院", "United States"),
    (25, "University of Wisconsin-Madison", "威斯康星大学麦迪逊分校", "United States"),
    (26, "University of Illinois at Urbana-Champaign", "伊利诺伊大学厄巴纳-香槟分校", "United States"),
    (27, "University of British Columbia", "不列颠哥伦比亚大学", "Canada"),
    (28, "McGill University", "麦吉尔大学", "Canada"),
    (29, "University of Melbourne", "墨尔本大学", "Australia"),
    (30, "King's College London", "伦敦国王学院", "United Kingdom"),
    (31, "University of Edinburgh", "爱丁堡大学", "United Kingdom"),
    (32, "University of Manchester", "曼彻斯特大学", "United Kingdom"),
    (33, "Boston University", "波士顿大学", "United States"),
    (34, "Brown University", "布朗大学", "United States"),
    (35, "University of California, Davis", "加州大学戴维斯分校", "United States"),
    (36, "University of California, Santa Barbara", "加州大学圣塔芭芭拉分校", "United States"),
    (37, "University of Texas at Austin", "德克萨斯大学奥斯汀分校", "United States"),
    (38, "University of Southern California", "南加州大学", "United States"),
    (39, "University of Minnesota Twin Cities", "明尼苏达大学双城分校", "United States"),
    (40, "Ohio State University", "俄亥俄州立大学", "United States"),
    (41, "University of Sydney", "悉尼大学", "Australia"),
    (42, "University of Queensland", "昆士兰大学", "Australia"),
    (43, "University of New South Wales", "新南威尔士大学", "Australia"),
    (44, "University of Amsterdam", "阿姆斯特丹大学", "Netherlands"),
    (45, "Technical University of Munich", "慕尼黑工业大学", "Germany"),
    (46, "Heidelberg University", "海德堡大学", "Germany"),
    (47, "Ludwig Maximilian University of Munich", "慕尼黑大学", "Germany"),
    (48, "University of Zurich", "苏黎世大学", "Switzerland"),
    (49, "ETH Zurich", "苏黎世联邦理工学院", "Switzerland"),
    (50, "Free University of Berlin", "柏林自由大学", "Germany"),
    (51, "Humboldt University of Berlin", "柏林洪堡大学", "Germany"),
    (52, "RWTH Aachen University", "亚琛工业大学", "Germany"),
    (53, "University of Tokyo", "东京大学", "Japan"),
    (54, "Kyoto University", "京都大学", "Japan"),
    (55, "Tsinghua University", "清华大学", "China"),
    (56, "Peking University", "北京大学", "China"),
    (57, "Fudan University", "复旦大学", "China"),
    (58, "Shanghai Jiao Tong University", "上海交通大学", "China"),
    (59, "Zhejiang University", "浙江大学", "China"),
    (60, "Seoul National University", "首尔大学", "South Korea"),
    (61, "National University of Singapore", "新加坡国立大学", "Singapore"),
    (62, "Nanyang Technological University", "南洋理工大学", "Singapore"),
    (63, "University of Hong Kong", "香港大学", "Hong Kong"),
    (64, "Chinese University of Hong Kong", "香港中文大学", "Hong Kong"),
    (65, "Hong Kong University of Science and Technology", "香港科技大学", "Hong Kong"),
    (66, "Hong Kong Polytechnic University", "香港理工大学", "Hong Kong"),
    (67, "City University of Hong Kong", "香港城市大学", "Hong Kong"),
    (68, "Karolinska Institutet", "卡罗林斯卡学院", "Sweden"),
    (69, "Uppsala University", "乌普萨拉大学", "Sweden"),
    (70, "Lund University", "隆德大学", "Sweden"),
    (71, "KTH Royal Institute of Technology", "皇家理工学院", "Sweden"),
    (72, "University of Copenhagen", "哥本哈根大学", "Denmark"),
    (73, "Technical University of Denmark", "丹麦技术大学", "Denmark"),
    (74, "University of Bristol", "布里斯托大学", "United Kingdom"),
    (75, "University of Warwick", "华威大学", "United Kingdom"),
    (76, "University of Glasgow", "格拉斯哥大学", "United Kingdom"),
    (77, "University of Southampton", "南安普顿大学", "United Kingdom"),
    (78, "University of Leeds", "利兹大学", "United Kingdom"),
    (79, "University of Sheffield", "谢菲尔德大学", "United Kingdom"),
    (80, "University of Nottingham", "诺丁汉大学", "United Kingdom"),
    (81, "University of Birmingham", "伯明翰大学", "United Kingdom"),
    (82, "Leiden University", "莱顿大学", "Netherlands"),
    (83, "Utrecht University", "乌得勒支大学", "Netherlands"),
    (84, "Erasmus University Rotterdam", "鹿特丹伊拉斯谟大学", "Netherlands"),
    (85, "Wageningen University", "瓦赫宁根大学", "Netherlands"),
    (86, "University of Vienna", "维也纳大学", "Austria"),
    (87, "University of Basel", "巴塞尔大学", "Switzerland"),
    (88, "University of Geneva", "日内瓦大学", "Switzerland"),
    (89, "Ecole Polytechnique Federale de Lausanne", "洛桑联邦理工学院", "Switzerland"),
    (90, "McMaster University", "麦克马斯特大学", "Canada"),
    (91, "University of Alberta", "阿尔伯塔大学", "Canada"),
    (92, "Western University", "韦仕敦大学", "Canada"),
    (93, "University of Waterloo", "滑铁卢大学", "Canada"),
    (94, "University of Calgary", "卡尔加里大学", "Canada"),
    (95, "University of Ottawa", "渥太华大学", "Canada"),
    (96, "Monash University", "蒙纳士大学", "Australia"),
    (97, "Australian National University", "澳大利亚国立大学", "Australia"),
    (98, "University of Western Australia", "西澳大利亚大学", "Australia"),
    (99, "University of Auckland", "奥克兰大学", "New Zealand"),
    (100, "University of Adelaide", "阿德莱德大学", "Australia"),
    (101, "Curtin University", "科廷大学", "Australia"),
    (102, "RMIT University", "皇家墨尔本理工大学", "Australia"),
    (103, "Macquarie University", "麦考瑞大学", "Australia"),
    (104, "University of Exeter", "埃克塞特大学", "United Kingdom"),
    (105, "University of Durham", "杜伦大学", "United Kingdom"),
    (106, "University of Bath", "巴斯大学", "United Kingdom"),
    (107, "University of St Andrews", "圣安德鲁斯大学", "United Kingdom"),
    (108, "University of York", "约克大学", "United Kingdom"),
    (109, "Trinity College Dublin", "都柏林圣三一学院", "Ireland"),
    (110, "University of Barcelona", "巴塞罗那大学", "Spain"),
    (111, "University of Bologna", "博洛尼亚大学", "Italy"),
    (112, "Sapienza University of Rome", "罗马第一大学", "Italy"),
    (113, "University of Padua", "帕多瓦大学", "Italy"),
    (114, "University of Milan", "米兰大学", "Italy"),
    (115, "Osaka University", "大阪大学", "Japan"),
    (116, "Tohoku University", "东北大学", "Japan"),
    (117, "Hokkaido University", "北海道大学", "Japan"),
    (118, "Nagoya University", "名古屋大学", "Japan"),
    (119, "Tokyo Institute of Technology", "东京工业大学", "Japan"),
    (120, "Waseda University", "早稻田大学", "Japan"),
    (121, "Keio University", "庆应义塾大学", "Japan"),
    (122, "Korea University", "高丽大学", "South Korea"),
    (123, "Yonsei University", "延世大学", "South Korea"),
    (124, "Korea Advanced Institute of Science and Technology", "韩国科学技术院", "South Korea"),
    (125, "Pohang University of Science and Technology", "浦项科技大学", "South Korea"),
    (126, "Sungkyunkwan University", "成均馆大学", "South Korea"),
    (127, "National Taiwan University", "台湾大学", "Taiwan"),
    (128, "National Tsing Hua University", "清华大学", "Taiwan"),
    (129, "National Cheng Kung University", "成功大学", "Taiwan"),
    (130, "Indian Institute of Technology Bombay", "孟买印度理工学院", "India"),
    (131, "Indian Institute of Technology Delhi", "德里印度理工学院", "India"),
    (132, "Indian Institute of Technology Madras", "马德拉斯印度理工学院", "India"),
    (133, "Indian Institute of Science", "印度科学学院", "India"),
    (134, "University of Delhi", "德里大学", "India"),
    (135, "University of Malaya", "马来亚大学", "Malaysia"),
    (136, "Chulalongkorn University", "朱拉隆功大学", "Thailand"),
    (137, "Mahidol University", "玛希隆大学", "Thailand"),
    (138, "Institut Teknologi Bandung", "万隆理工学院", "Indonesia"),
    (139, "University of Indonesia", "印度尼西亚大学", "Indonesia"),
    (140, "Gadjah Mada University", "加查马达大学", "Indonesia"),
    (141, "University of the Philippines", "菲律宾大学", "Philippines"),
    (142, "University of Colombo", "科伦坡大学", "Sri Lanka"),
    (143, "University of Dhaka", "达卡大学", "Bangladesh"),
    (144, "Nanjing University", "南京大学", "China"),
    (145, "Wuhan University", "武汉大学", "China"),
    (146, "Sun Yat-sen University", "中山大学", "China"),
    (147, "Harbin Institute of Technology", "哈尔滨工业大学", "China"),
    (148, "Xi'an Jiaotong University", "西安交通大学", "China"),
    (149, "Tongji University", "同济大学", "China"),
    (150, "Beijing Institute of Technology", "北京理工大学", "China"),
    (151, "Southeast University", "东南大学", "China"),
    (152, "Tianjin University", "天津大学", "China"),
    (153, "Huazhong University of Science and Technology", "华中科技大学", "China"),
    (154, "Sichuan University", "四川大学", "China"),
    (155, "Beihang University", "北京航空航天大学", "China"),
    (156, "Dalian University of Technology", "大连理工大学", "China"),
    (157, "Chongqing University", "重庆大学", "China"),
    (158, "Jilin University", "吉林大学", "China"),
    (159, "Shandong University", "山东大学", "China"),
    (160, "Nankai University", "南开大学", "China"),
    (161, "Xiamen University", "厦门大学", "China"),
    (162, "Central South University", "中南大学", "China"),
    (163, "Beijing Normal University", "北京师范大学", "China"),
    (164, "East China Normal University", "华东师范大学", "China"),
    (165, "Indiana University Bloomington", "印第安纳大学伯明顿分校", "United States"),
    (166, "University of Colorado Boulder", "科罗拉多大学博尔德分校", "United States"),
    (167, "University of Florida", "佛罗里达大学", "United States"),
    (168, "University of Pittsburgh", "匹兹堡大学", "United States"),
    (169, "Pennsylvania State University", "宾夕法尼亚州立大学", "United States"),
    (170, "Purdue University", "普渡大学", "United States"),
    (171, "University of Arizona", "亚利桑那大学", "United States"),
    (172, "Arizona State University", "亚利桑那州立大学", "United States"),
    (173, "University of Virginia", "弗吉尼亚大学", "United States"),
    (174, "Georgetown University", "乔治城大学", "United States"),
    (175, "University of Notre Dame", "圣母大学", "United States"),
    (176, "Washington University in St. Louis", "圣路易斯华盛顿大学", "United States"),
    (177, "Emory University", "埃默里大学", "United States"),
    (178, "Vanderbilt University", "范德堡大学", "United States"),
    (179, "Rice University", "莱斯大学", "United States"),
    (180, "University of Rochester", "罗切斯特大学", "United States"),
    (181, "Tufts University", "塔夫茨大学", "United States"),
    (182, "Boston College", "波士顿学院", "United States"),
    (183, "University of California, Irvine", "加州大学欧文分校", "United States"),
    (184, "University of California, Santa Cruz", "加州大学圣克鲁兹分校", "United States"),
    (185, "University of Otago", "奥塔哥大学", "New Zealand"),
    (186, "University of Warsaw", "华沙大学", "Poland"),
    (187, "Jagiellonian University", "雅盖隆大学", "Poland"),
    (188, "Charles University", "查理大学", "Czech Republic"),
    (189, "University of Belgrade", "贝尔格莱德大学", "Serbia"),
    (190, "University of Ljubljana", "卢布尔雅那大学", "Slovenia"),
    (191, "University of Bucharest", "布加勒斯特大学", "Romania"),
    (192, "Eotvos Lorand University", "罗兰大学", "Hungary"),
    (193, "University of Helsinki", "赫尔辛基大学", "Finland"),
    (194, "University of Oslo", "奥斯陆大学", "Norway"),
    (195, "Aarhus University", "奥胡斯大学", "Denmark"),
    (196, "University of Cape Town", "开普敦大学", "South Africa"),
    (197, "University of Witwatersrand", "金山大学", "South Africa"),
    (198, "Stellenbosch University", "斯泰伦博斯大学", "South Africa"),
    (199, "American University of Beirut", "贝鲁特美国大学", "Lebanon"),
    (200, "University of Haifa", "海法大学", "Israel"),
]

# ─────────────────────────────────────────────────────────────────────────────
# Name normalization for matching
# ─────────────────────────────────────────────────────────────────────────────
def normalize(s):
    """Remove common suffixes, punctuation, and normalize spacing."""
    if not s:
        return ""
    s = s.lower().strip()
    for suffix in [
        " university", " institute of technology", " institute",
        " college", " of science and technology", " national university",
        " technical university", " university of technology"
    ]:
        if s.endswith(suffix):
            s = s[:-len(suffix)]
    s = re.sub(r"[^\w\s\u4e00-\u9fff]", " ", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s

def similarity(a, b):
    return SequenceMatcher(None, a, b).ratio()

def build_lookup():
    """Build lookup table from database."""
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    cur = conn.cursor()
    cur.execute("SELECT id, name, name_cn, level, country FROM schools WHERE level='university'")
    rows = cur.fetchall()
    conn.close()
    return [(r['id'], r['name'], r['name_cn'], r['country']) for r in rows]

def find_best_match(rank_name, rank_cn, rank_country, lookup, name_to_ids):
    """Try exact and fuzzy matching for a university."""
    n_name = normalize(rank_name)
    n_cn = normalize(rank_cn) if rank_cn else ""
    
    # Direct normalized key lookup
    if n_name in name_to_ids:
        candidates = name_to_ids[n_name]
        if len(candidates) == 1:
            return candidates[0][0], 1.0
        for c in candidates:
            if c[3] == rank_country:
                return c[0], 1.0
        return candidates[0][0], 1.0
    
    if n_cn and n_cn in name_to_ids:
        candidates = name_to_ids[n_cn]
        if len(candidates) == 1:
            return candidates[0][0], 1.0
        for c in candidates:
            if c[3] == rank_country:
                return c[0], 1.0
        return candidates[0][0], 1.0
    
    # Fuzzy match
    all_candidates = [(uid, uname, ucname) for uid, uname, ucname, _ in lookup]
    best_uid, best_score = None, 0
    
    for uid, uname, ucname in all_candidates:
        scores = []
        n_uname = normalize(uname)
        if n_uname:
            s = similarity(n_name, n_uname)
            if s > 0.6:
                scores.append(s)
        if ucname:
            n_ucname = normalize(ucname)
            if n_ucname:
                s = similarity(n_name, n_ucname)
                if s > 0.6:
                    scores.append(s)
        if scores and max(scores) > best_score:
            best_score = max(scores)
            best_uid = uid
    
    if best_score >= 0.75:
        return best_uid, best_score
    return None, best_score

def import_rankings():
    print("🏆 Building university lookup table...")
    lookup = build_lookup()
    print(f"   Found {len(lookup)} universities in database")
    
    # Build name → candidates mapping
    name_to_ids = {}
    for uid, uname, ucname, ucountry in lookup:
        for key in [normalize(uname), normalize(ucname) if ucname else ""]:
            if key:
                if key not in name_to_ids:
                    name_to_ids[key] = []
                name_to_ids[key].append((uid, uname, ucname, ucountry))
    
    # Collect all updates
    updates = {}  # school_id -> {ranking_col: rank_value}
    matched = {'qs': 0, 'usnews': 0, 'the': 0, 'arwu': 0, 'cwur': 0}
    not_matched = {'qs': [], 'usnews': [], 'the': [], 'arwu': [], 'cwur': []}
    
    ranking_sources = [
        ('qs', QS_2026),
        ('usnews', USNEWS_2026),
        ('the', THE_2026),
        ('arwu', ARWU_2025),
        ('cwur', CWUR_2025),
    ]
    
    for ranking_name, ranking_data in ranking_sources:
        print(f"\n📊 Processing {ranking_name.upper()} ({len(ranking_data)} universities)...")
        found = 0
        for rank, name, cn, country in ranking_data:
            uid, score = find_best_match(name, cn, country, lookup, name_to_ids)
            if uid:
                if uid not in updates:
                    updates[uid] = {}
                updates[uid][f'{ranking_name}_rank'] = rank
                found += 1
            else:
                not_matched[ranking_name].append((rank, name, cn, country))
        matched[ranking_name] = found
        print(f"   Matched: {found}/{len(ranking_data)}")
    
    # Apply updates
    print(f"\n💾 Applying updates to {len(updates)} universities...")
    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()
    
    year_map = {'qs': 2026, 'usnews': 2026, 'the': 2026, 'arwu': 2025, 'cwur': 2025}
    
    for uid, rank_updates in updates.items():
        cols = list(rank_updates.keys())
        vals = list(rank_updates.values())
        years = [year_map[c.replace('_rank', '')] for c in cols]
        set_clause = ', '.join([f"{c} = ?" for c in cols] + [f"{c.replace('_rank','_year')} = ?" for c in cols])
        all_vals = vals + years + [uid]
        sql = f"UPDATE schools SET {set_clause} WHERE id = ?"
        try:
            cur.execute(sql, all_vals)
        except Exception as e:
            print(f"  Error updating id={uid}: {e}")
    
    conn.commit()
    
    # Final stats
    total_ranked = cur.execute("""
        SELECT COUNT(*) FROM schools WHERE level='university' AND 
        (qs_rank IS NOT NULL OR usnews_rank IS NOT NULL OR 
         the_rank IS NOT NULL OR arwu_rank IS NOT NULL OR cwur_rank IS NOT NULL)
    """).fetchone()[0]
    
    conn.close()
    
    print(f"\n{'='*65}")
    print(f"📊 Rankings Import Complete!")
    print(f"{'='*65}")
    print(f"\n  ✅ Updated: {len(updates)} universities")
    print(f"\n  📈 Match Statistics:")
    for r, c in matched.items():
        total = len(ranking_sources[[x[0] for x in ranking_sources].index(r)][1])
        print(f"     {r.upper():8s}: {c}/{total} matched")
    
    print(f"\n  🎯 Total universities with rankings: {total_ranked}")
    
    for r, nm in not_matched.items():
        if nm:
            print(f"\n  ⚠️  {r.upper()} not matched ({len(nm)}):")
            for rank, name, cn, country in nm[:3]:
                print(f"       #{rank} {name} ({country})")

if __name__ == '__main__':
    import_rankings()
