#!/usr/bin/env python3
"""
导入东区学校数据到数据库
参考: https://www.edb.gov.hk/en/student-parents/sch-info/sch-search/schlist-by-district/school-list-hke.html
"""

import sqlite3
from datetime import datetime

def import_eastern_schools():
    """导入东区学校数据"""
    conn = sqlite3.connect('database.db')
    cursor = conn.cursor()
    
    print("=" * 60)
    print("导入东区 (Eastern) 学校数据")
    print("=" * 60)
    
    # 东区学校数据
    eastern_schools = [
        # === GOVERNMENT SECONDARY SCHOOLS ===
        {
            "name": "BELILIOS PUBLIC SCHOOL",
            "name_cn": "庇理羅士女子中學",
            "address": "51 TIN HAU TEMPLE ROAD HONG KONG",
            "phone": "25718018",
            "fax": "25785698",
            "supervisor": "MS NG HOI YAN (吳凱茵女士)",
            "principal": "MS WONG FEI (王徽女士)",
            "gender": "GIRLS",
            "level": "middle",
            "finance_type": "Government",
            "district": "Eastern",
            "school_code": "510378 / 0001",
        },
        {
            "name": "CLEMENTI SECONDARY SCHOOL",
            "name_cn": "金文泰中學",
            "address": "30 FORTRESS HILL ROAD NORTH POINT HONG KONG",
            "phone": "25706411",
            "fax": "25785719",
            "supervisor": "MISS MA SUET YEE (馬雪兒小姐)",
            "principal": "MR LEE LUNG HEI MICHAEL (李隆熙先生)",
            "gender": "CO-ED",
            "level": "middle",
            "finance_type": "Government",
            "district": "Eastern",
            "school_code": "510033 / 0001",
        },
        {
            "name": "SHAU KEI WAN EAST GOVERNMENT SEC SCH",
            "name_cn": "筲箕灣東官立中學",
            "address": "40 CHAI WAN ROAD SHAUKEIWAN HONG KONG",
            "phone": "25602677",
            "fax": "25689865",
            "supervisor": "MS HO YIN PING (何燕萍女士)",
            "principal": "MS TANG TZE KWAN TERESA (鄧子筠女士)",
            "gender": "CO-ED",
            "level": "middle",
            "finance_type": "Government",
            "district": "Eastern",
            "school_code": "510220 / 0001",
        },
        {
            "name": "SHAU KEI WAN GOVERNMENT SECONDARY SCHOOL",
            "name_cn": "筲箕灣官立中學",
            "address": "42 CHAI WAN ROAD SHAUKEIWAN HONG KONG",
            "phone": "25603544",
            "fax": "25689708",
            "supervisor": "MS HO YIN PING (何燕萍女士)",
            "principal": "MS YAN KIN FOON ALICE (殷見歡女士)",
            "gender": "CO-ED",
            "level": "middle",
            "finance_type": "Government",
            "district": "Eastern",
            "school_code": "510440 / 0001",
        },
        
        # === AIDED SECONDARY SCHOOLS ===
        {
            "name": "CANOSSA COLLEGE",
            "name_cn": "嘉諾撒書院",
            "address": "10 HOI CHAK STREET QUARRY BAY HONG KONG",
            "phone": "25630272",
            "fax": "25628910",
            "supervisor": "-",
            "principal": "-",
            "gender": "GIRLS",
            "level": "middle",
            "finance_type": "Aided",
            "district": "Eastern",
            "school_code": "133124 / 0001",
        },
        {
            "name": "CARITAS CHAI WAN MARDEN FDN SEC SCH",
            "name_cn": "明愛柴灣馬登基金中學",
            "address": "330 SAN HA STREET CHAI WAN HONG KONG",
            "phone": "25584133",
            "fax": "28984423",
            "supervisor": "-",
            "principal": "MS HUNG WING CHEE (洪詠慈女士)",
            "gender": "CO-ED",
            "level": "middle",
            "finance_type": "Aided",
            "district": "Eastern",
            "school_code": "270040 / 0001",
        },
        {
            "name": "CCC KWEI WAH SHAN COLLEGE",
            "name_cn": "中華基督教會桂華山中學",
            "address": "62 CLOUD VIEW ROAD NORTH POINT HONG KONG",
            "phone": "25711285",
            "fax": "28070085",
            "supervisor": "MR AU YEUNG KA KEUNG (歐陽家強先生)",
            "principal": "MR WONG CHUNG LEUNG (黃仲良先生)",
            "gender": "CO-ED",
            "level": "middle",
            "finance_type": "Aided",
            "district": "Eastern",
            "school_code": "170216 / 0001",
        },
        {
            "name": "CHEUNG CHUK SHAN COLLEGE",
            "name_cn": "張祝珊英文中學",
            "address": "11 CLOUD VIEW ROAD NORTH POINT HONG KONG",
            "phone": "25706665",
            "fax": "25120429",
            "supervisor": "-",
            "principal": "-",
            "gender": "CO-ED",
            "level": "middle",
            "finance_type": "Aided",
            "district": "Eastern",
            "school_code": "170186 / 0001",
        },
        {
            "name": "CHONG GENE HANG COLLEGE",
            "name_cn": "張振興伉儷書院",
            "address": "12 CHEUNG MAN ROAD CHAI WAN HONG KONG",
            "phone": "25566081",
            "fax": "28984494",
            "supervisor": "MR HO KONG HIN (何江顯先生)",
            "principal": "MR WONG SAI YIU (黃世堯先生)",
            "gender": "CO-ED",
            "level": "middle",
            "finance_type": "Aided",
            "district": "Eastern",
            "school_code": "170526 / 0001",
        },
        {
            "name": "CNEC LAU WING SANG SECONDARY SCH",
            "name_cn": "中華傳道會劉永生中學",
            "address": "323 SAN HA STREET CHAI WAN HONG KONG",
            "phone": "27156333",
            "fax": "25569126",
            "supervisor": "-",
            "principal": "MR MUI CHI YIP HEZEKIAH (梅志業先生)",
            "gender": "CO-ED",
            "level": "middle",
            "finance_type": "Aided",
            "district": "Eastern",
            "school_code": "529990 / 0002",
        },
        {
            "name": "COGNITIO COLLEGE (HONG KONG)",
            "name_cn": "文理書院（香港）",
            "address": "4 SUI MAN ROAD CHAI WAN HONG KONG",
            "phone": "25567413",
            "fax": "28977177",
            "supervisor": "MADAM AU-YEUNG WAI YIN (歐陽惠賢女士)",
            "principal": "MR AU YEUNG SING LEUNG (歐陽昇良先生)",
            "gender": "CO-ED",
            "level": "middle",
            "finance_type": "Aided",
            "district": "Eastern",
            "school_code": "212431 / 0001",
        },
        {
            "name": "FORTRESS HILL METHODIST SECONDARY SCHOOL",
            "name_cn": "炮台山循道衛理中學",
            "address": "19 FORTRESS HILL ROAD NORTH POINT HONG KONG",
            "phone": "25107688",
            "fax": "25109677",
            "supervisor": "-",
            "principal": "MR SHUM LAP PING (沈立平先生)",
            "gender": "CO-ED",
            "level": "middle",
            "finance_type": "Aided",
            "district": "Eastern",
            "school_code": "516961 / 0001",
        },
        {
            "name": "FUKIEN SECONDARY SCHOOL (SIU SAI WAN)",
            "name_cn": "福建中學（小西灣）",
            "address": "2 FU YEE ROAD SIU SAI WAN CHAI WAN HONG KONG",
            "phone": "25669223",
            "fax": "25669020",
            "supervisor": "-",
            "principal": "-",
            "gender": "CO-ED",
            "level": "middle",
            "finance_type": "Aided",
            "district": "Eastern",
            "school_code": "524590 / 0001",
        },
        {
            "name": "HENRIETTA SECONDARY SCHOOL",
            "name_cn": "顯理中學",
            "address": "2 CITY GARDEN ROAD NORTH POINT HONG KONG",
            "phone": "25701466",
            "fax": "25034603",
            "supervisor": "MR CHIU CHI KWAN WARREN (趙之琨先生)",
            "principal": "MR NG HO YIN (吳浩然先生)",
            "gender": "CO-ED",
            "level": "middle",
            "finance_type": "Aided",
            "district": "Eastern",
            "school_code": "511943 / 0001",
        },
        {
            "name": "HONG KONG CHINESE WOMEN'S CLUB COLLEGE",
            "name_cn": "香港中國婦女會中學",
            "address": "2B TAI CHEONG STREET SAI WAN HO HONG KONG",
            "phone": "25684817",
            "fax": "25680336",
            "supervisor": "MS MAN YEE FUN EVELYN (文綺芬女士)",
            "principal": "MR YEUNG CHI KEUNG (楊志强先生)",
            "gender": "CO-ED",
            "level": "middle",
            "finance_type": "Aided",
            "district": "Eastern",
            "school_code": "215139 / 0001",
        },
        {
            "name": "ISLAMIC KASIM TUET MEMORIAL COLLEGE",
            "name_cn": "伊斯蘭脫維善紀念中學",
            "address": "22 TSUI WAN STREET CHAI WAN HONG KONG",
            "phone": "25709066",
            "fax": "28873164",
            "supervisor": "-",
            "principal": "MS HO SAU YIN ZAREENAH (何秀賢女士)",
            "gender": "CO-ED",
            "level": "middle",
            "finance_type": "Aided",
            "district": "Eastern",
            "school_code": "522082 / 0001",
        },
        {
            "name": "LINGNAN HANG YEE MEMORIAL SECONDARY SCH",
            "name_cn": "嶺南衡怡紀念中學",
            "address": "31 SIU SAI WAN ROAD CHAI WAN HONG KONG",
            "phone": "25764852",
            "fax": "28824540",
            "supervisor": "MR CHIU ERNEST TIN CHUNG (招天聰先生)",
            "principal": "MR WONG WAI HOU (王偉豪先生)",
            "gender": "CO-ED",
            "level": "middle",
            "finance_type": "Aided",
            "district": "Eastern",
            "school_code": "171000 / 0002",
        },
        {
            "name": "LINGNAN SECONDARY SCHOOL",
            "name_cn": "嶺南中學",
            "address": "6 SHING HONG LANE, HENG FA CHUEN HONG KONG",
            "phone": "28916966",
            "fax": "25747597",
            "supervisor": "-",
            "principal": "MS CHUNG WAI CHING (鍾慧晶女士)",
            "gender": "CO-ED",
            "level": "middle",
            "finance_type": "Aided",
            "district": "Eastern",
            "school_code": "171042 / 0002",
        },
        {
            "name": "MAN KIU COLLEGE",
            "name_cn": "閩僑中學",
            "address": "81 CLOUD VIEW ROAD HONG KONG",
            "phone": "25784523",
            "fax": "25128349",
            "supervisor": "-",
            "principal": "-",
            "gender": "CO-ED",
            "level": "middle",
            "finance_type": "Aided",
            "district": "Eastern",
            "school_code": "214590 / 0001",
        },
        {
            "name": "MUNSANG COLLEGE (HONG KONG ISLAND)",
            "name_cn": "港島民生書院",
            "address": "26 TAI ON STREET SAI WAN HO HONG KONG",
            "phone": "25671666",
            "fax": "25671338",
            "supervisor": "-",
            "principal": "-",
            "gender": "CO-ED",
            "level": "middle",
            "finance_type": "Aided",
            "district": "Eastern",
            "school_code": "530018 / 0001",
        },
        {
            "name": "PRECIOUS BLOOD SECONDARY SCHOOL",
            "name_cn": "寶血女子中學",
            "address": "338 SAN HA STREET CHAI WAN HONG KONG",
            "phone": "25704172",
            "fax": "25782491",
            "supervisor": "MR CHEUNG WING MING FRANCIS (張永明先生)",
            "principal": "MS NGAN LAI PING (顏麗萍女士)",
            "gender": "GIRLS",
            "level": "middle",
            "finance_type": "Aided",
            "district": "Eastern",
            "school_code": "513300 / 0002",
        },
        {
            "name": "SALESIAN ENGLISH SCHOOL",
            "name_cn": "慈幼英文學校",
            "address": "16 CHAI WAN ROAD SHAUKEIWAN HONG KONG",
            "phone": "25602134",
            "fax": "25689697",
            "supervisor": "MR YEUNG CHO LAW SAVIO (楊祖羅先生)",
            "principal": "MS TO YUK YIN JOSEPHINE (杜玉燕女士)",
            "gender": "BOYS",
            "level": "middle",
            "finance_type": "Aided",
            "district": "Eastern",
            "school_code": "210528 / 0001",
        },
        {
            "name": "SKH LI FOOK HING SECONDARY SCHOOL",
            "name_cn": "聖公會李福慶中學",
            "address": "TSUI WAN ESTATE TSUI WAN STREET CHAI WAN HONG KONG",
            "phone": "25605678",
            "fax": "28865730",
            "supervisor": "MR LO KIN MING (盧健明先生)",
            "principal": "-",
            "gender": "CO-ED",
            "level": "middle",
            "finance_type": "Aided",
            "district": "Eastern",
            "school_code": "518395 / 0001",
        },
        {
            "name": "ST JOAN OF ARC SECONDARY SCHOOL",
            "name_cn": "聖貞德中學",
            "address": "55 BRAEMAR HILL ROAD NORTH POINT HONG KONG",
            "phone": "25785984",
            "fax": "25785725",
            "supervisor": "MR CHUEN KWOK WAI SANTIAGO (全國偉先生)",
            "principal": "MR YUEN CHEUNG OI (阮章凱先生)",
            "gender": "CO-ED",
            "level": "middle",
            "finance_type": "Aided",
            "district": "Eastern",
            "school_code": "133469 / 0001",
        },
        {
            "name": "ST MARK'S SCHOOL",
            "name_cn": "聖馬可中學",
            "address": "18 OI YIN STREET, ALDRICH BAY SHAUKEIWAN HONG KONG",
            "phone": "25601262",
            "fax": "25675809",
            "supervisor": "MR YUEN HOI KAU (袁海球先生)",
            "principal": "MS CHAN SZE YAN (陳思茵女士)",
            "gender": "CO-ED",
            "level": "middle",
            "finance_type": "Aided",
            "district": "Eastern",
            "school_code": "514110 / 0002",
        },
        {
            "name": "THE METHODIST CHURCH HK WESLEY COLLEGE",
            "name_cn": "衞理中學",
            "address": "33 SIU SAI WAN ROAD CHAI WAN HONG KONG",
            "phone": "28965079",
            "fax": "25057601",
            "supervisor": "MR TSANG SIU KEI (曾兆基先生)",
            "principal": "MR NAM CHING SZE (藍正思先生)",
            "gender": "CO-ED",
            "level": "middle",
            "finance_type": "Aided",
            "district": "Eastern",
            "school_code": "170810 / 0002",
        },
        
        # === DIRECT SUBSIDY SECONDARY SCHOOLS ===
        {
            "name": "HON WAH COLLEGE",
            "name_cn": "漢華中學",
            "address": "3 HARMONY ROAD SIU SAI WAN HONG KONG",
            "phone": "28171746",
            "fax": "28176453",
            "supervisor": "MS TSUI YEE WAN LINDA (崔綺雲女士)",
            "principal": "MR KWAN WING BUN (關穎斌先生)",
            "gender": "CO-ED",
            "level": "middle",
            "finance_type": "Direct",
            "district": "Eastern",
            "school_code": "512079 / 0002",
        },
        {
            "name": "KIANGSU-CHEKIANG COLLEGE",
            "name_cn": "蘇浙公學",
            "address": "20 BRAEMAR HILL ROAD HONG KONG",
            "phone": "25702261",
            "fax": "25100264",
            "supervisor": "MR WONG PO MING (王寶明先生)",
            "principal": "MR FONG CHUNG LUN (方仲倫先生)",
            "gender": "CO-ED",
            "level": "middle",
            "finance_type": "Direct",
            "district": "Eastern",
            "school_code": "211338 / 0001",
        },
        {
            "name": "PUI KIU MIDDLE SCHOOL",
            "name_cn": "培僑中學",
            "address": "190 TIN HAU TEMPLE ROAD NORTH POINT HONG KONG",
            "phone": "25662317",
            "fax": "28878737",
            "supervisor": "MR TSANG YOK SING JASPER (曾鈺成先生)",
            "principal": "MR NG WUN KIT (伍煥杰先生)",
            "gender": "CO-ED",
            "level": "middle",
            "finance_type": "Direct",
            "district": "Eastern",
            "school_code": "513369 / 0001",
        },
        {
            "name": "THE CHINESE FOUNDATION SECONDARY SCHOOL",
            "name_cn": "中華基金中學",
            "address": "9 HARMONY ROAD SIU SAI WAN CHAI WAN HONG KONG",
            "phone": "29047322",
            "fax": "28922777",
            "supervisor": "MS WONG YU POK MARINA (黃汝璞女士)",
            "principal": "MR HO TIK SHUN (何廸信先生)",
            "gender": "CO-ED",
            "level": "middle",
            "finance_type": "Direct",
            "district": "Eastern",
            "school_code": "536598 / 0001",
        },
        
        # === GOVERNMENT PRIMARY SCHOOLS ===
        {
            "name": "ALDRICH BAY GOVERNMENT PRI SCH",
            "name_cn": "愛秩序灣官立小學",
            "address": "1 OI LAI STREET SHAU KEI WAN HONG KONG",
            "phone": "25611118",
            "fax": "25628437",
            "supervisor": "MS WENDY LEUNG (梁蘊儀女士)",
            "principal": "MR CHUI KA CHEUNG (崔家祥先生)",
            "gender": "CO-ED",
            "level": "elementary",
            "finance_type": "Government",
            "district": "Eastern",
            "school_code": "534196 / 0001",
        },
        {
            "name": "NORTH POINT GOVERNMENT PRIMARY SCHOOL",
            "name_cn": "北角官立小學",
            "address": "888 KING'S ROAD NORTH POINT HONG KONG",
            "phone": "25617130",
            "fax": "25628814",
            "supervisor": "MR LEUNG PAK WAI (梁柏偉先生)",
            "principal": "MS IP WAN TING BELINDA (葉韻婷女士)",
            "gender": "CO-ED",
            "level": "elementary",
            "finance_type": "Government",
            "district": "Eastern",
            "school_code": "510157 / 0001",
        },
        {
            "name": "SHAU KEI WAN GOVERNMENT PRIMARY SCHOOL",
            "name_cn": "筲箕灣官立小學",
            "address": "19 MAIN STREET EAST SHAUKEIWAN HONG KONG",
            "phone": "25692532",
            "fax": "25689504",
            "supervisor": "MS LEUNG WING SHAN MAGNOLIA (梁詠珊女士)",
            "principal": "MR WONG WAI KIT (王偉傑先生)",
            "gender": "CO-ED",
            "level": "elementary",
            "finance_type": "Government",
            "district": "Eastern",
            "school_code": "510629 / 0001",
        },
        
        # === AIDED PRIMARY SCHOOLS (部分) ===
        {
            "name": "BUDDHIST CHUNG WAH KORNHILL PRI SCH",
            "name_cn": "佛教中華康山學校",
            "address": "2 HONG YUE STREET QUARRY BAY HONG KONG",
            "phone": "28844115",
            "fax": "25679897",
            "supervisor": "VEN SIK YIN CHI (釋演慈女法師)",
            "principal": "MR MA CHUNG TSUN (馬中駿先生)",
            "gender": "CO-ED",
            "level": "elementary",
            "finance_type": "Aided",
            "district": "Eastern",
            "school_code": "511250 / 0001",
        },
        {
            "name": "CANOSSA SCHOOL (HONG KONG)",
            "name_cn": "香港嘉諾撒學校",
            "address": "8 HOI CHAK STREET QUARRY BAY HONG KONG",
            "phone": "25610115",
            "fax": "25627840",
            "supervisor": "SR SHIU YUEN FUN MAGDALEN (邵苑芬修女)",
            "principal": "MS FONG PIK YIN SIKKIE (方碧燕女士)",
            "gender": "CO-ED",
            "level": "elementary",
            "finance_type": "Aided",
            "district": "Eastern",
            "school_code": "511358 / 0001",
        },
        {
            "name": "CCC KEI WAN PRIMARY SCHOOL",
            "name_cn": "中華基督教會基灣小學",
            "address": "63 SAI WAN HO STREET SHAU KEI WAN HONG KONG",
            "phone": "25608007",
            "fax": "28854050",
            "supervisor": "MR YUNG CHUEN HUNG (翁傳鏗先生)",
            "principal": "MR LAM WAI HUNG (林偉雄先生)",
            "gender": "CO-ED",
            "level": "elementary",
            "finance_type": "Aided",
            "district": "Eastern",
            "school_code": "510858 / 0001",
        },
        {
            "name": "CCC KEI WAN PRIMARY SCHOOL (ALDRICH BAY)",
            "name_cn": "中華基督教會基灣小學（愛蝶灣）",
            "address": "39 OI SHUN ROAD SHAUKEIWAN HONG KONG",
            "phone": "29154140",
            "fax": "25390988",
            "supervisor": "MS SHUM KWOK YAN DAISY (岑國欣女士)",
            "principal": "MS WONG CHING MAN (黃靜雯女士)",
            "gender": "CO-ED",
            "level": "elementary",
            "finance_type": "Aided",
            "district": "Eastern",
            "school_code": "543306 / 0001",
        },
        {
            "name": "CHAN'S CREATIVE SCHOOL (HONG KONG ISLAND)",
            "name_cn": "啓基學校（港島）",
            "address": "82 MARBLE ROAD NORTH POINT HONG KONG",
            "phone": "25614302",
            "fax": "25610839",
            "supervisor": "MR MA WAI HUNG VINCENT (馬偉雄先生)",
            "principal": "MS CHENG WAI KI (鄭惠琪女士)",
            "gender": "CO-ED",
            "level": "elementary",
            "finance_type": "Aided",
            "district": "Eastern",
            "school_code": "513083 / 0001",
        },
        {
            "name": "CHINESE METHODIST SCHOOL (NORTH POINT)",
            "name_cn": "北角循道學校",
            "address": "15 PAK FUK ROAD NORTH POINT HONG KONG",
            "phone": "25619693",
            "fax": "25627860",
            "supervisor": "MR LEUNG CHEUK FAI (梁灼輝先生)",
            "principal": "MR CHENG KA MING (鄭家明先生)",
            "gender": "CO-ED",
            "level": "elementary",
            "finance_type": "Aided",
            "district": "Eastern",
            "school_code": "510750 / 0001",
        },
    ]
    
    now = datetime.now().isoformat()
    inserted = 0
    updated = 0
    
    for school in eastern_schools:
        # 检查是否已存在
        cursor.execute("SELECT id FROM schools WHERE name = ? AND district = ?", 
                      (school['name'], school.get('district', '')))
        existing = cursor.fetchone()
        
        if existing:
            # 更新
            cursor.execute("""
                UPDATE schools SET
                    name_cn = ?,
                    address = ?,
                    phone = ?,
                    fax = ?,
                    supervisor = ?,
                    principal = ?,
                    gender = ?,
                    level = ?,
                    finance_type = ?,
                    district = ?,
                    school_code = ?,
                    source = 'edb',
                    updated_at = ?
                WHERE id = ?
            """, (
                school['name_cn'],
                school['address'],
                school['phone'],
                school['fax'],
                school['supervisor'],
                school['principal'],
                school['gender'],
                school['level'],
                school['finance_type'],
                school['district'],
                school['school_code'],
                now,
                existing[0]
            ))
            updated += 1
        else:
            # 插入
            cursor.execute("""
                INSERT INTO schools (
                    name, name_cn, region, country, city, address, phone, fax, supervisor, principal,
                    gender, level, finance_type, district, school_code, source,
                    created_at, updated_at
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """, (
                school['name'], school['name_cn'], 'Hong Kong', 'China', 'Hong Kong',
                school['address'], school['phone'], school['fax'], school['supervisor'], school['principal'],
                school['gender'], school['level'], school['finance_type'],
                school['district'], school['school_code'], 'edb',
                now, now
            ))
            inserted += 1
    
    conn.commit()
    
    # 统计
    cursor.execute("SELECT COUNT(*) FROM schools WHERE source = 'edb'")
    total_edb = cursor.fetchone()[0]
    
    cursor.execute("SELECT COUNT(*) FROM schools WHERE district = 'Eastern'")
    eastern_count = cursor.fetchone()[0]
    
    conn.close()
    
    print(f"\n导入完成!")
    print(f"  新增: {inserted} 所")
    print(f"  更新: {updated} 所")
    print(f"  EDB来源总计: {total_edb} 所")
    print(f"  东区总计: {eastern_count} 所")
    
    return inserted + updated

if __name__ == '__main__':
    import_eastern_schools()
